; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

define i32 @main(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  block1:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[CMP]], label [[BLOCK2:%.*]], label [[BLOCK3:%.*]]
; CHECK:       block2:
; CHECK-NEXT:    [[DEAD_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label [[BLOCK4:%.*]]
; CHECK:       block3:
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    br label [[BLOCK4]]
; CHECK:       block4:
; CHECK-NEXT:    [[DEAD:%.*]] = phi i32 [ 0, [[BLOCK3]] ], [ [[DEAD_PRE]], [[BLOCK2]] ]
; CHECK-NEXT:    ret i32 [[DEAD]]
;
block1:
  %z = load i32, ptr %p
  %cmp = icmp eq i32 %x, %y
  br i1 %cmp, label %block2, label %block3

block2:
  br label %block4

block3:
  %b = bitcast i32 0 to i32
  store i32 %b, ptr %p
  br label %block4

block4:
  %DEAD = load i32, ptr %p
  ret i32 %DEAD
}

