; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; PR1996

%struct.anon = type { i32, i8, i8, i8, i8 }

define i32 @a() {
; CHECK-LABEL: define i32 @a() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = alloca [[STRUCT_ANON:%.*]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[C]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = or i32 [[TMP2]], 11
; CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[TMP3]], -21
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[CALL:%.*]] = call i32 (...) @x(ptr [[C]])
; CHECK-NEXT:    ret i32 undef
;
entry:
  %c = alloca %struct.anon                ; <ptr> [#uses=2]
  %tmp = getelementptr %struct.anon, ptr %c, i32 0, i32 0             ; <ptr> [#uses=1]
  %tmp1 = getelementptr i32, ptr %tmp, i32 1          ; <ptr> [#uses=2]
  %tmp2 = load i32, ptr %tmp1, align 4                ; <i32> [#uses=1]
  %tmp3 = or i32 %tmp2, 11                ; <i32> [#uses=1]
  %tmp4 = and i32 %tmp3, -21              ; <i32> [#uses=1]
  store i32 %tmp4, ptr %tmp1, align 4
  %call = call i32 (...) @x( ptr %c )          ; <i32> [#uses=0]
  ret i32 undef
}


declare i32 @x(...)
