; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test the three assumption modes: optimistic, balanced, pessimistic.
;
; Optimistic and balanced start with all values in TOPClass (optimistic about values).
; Pessimistic starts with each value in its own singleton class.
; Balanced and pessimistic mark all blocks/edges reachable from the start.
; Optimistic discovers reachability during iteration.
;
; RUN: opt < %s -passes=newgvn -newgvn-assumption=optimistic -S | FileCheck %s --check-prefix=OPT
; RUN: opt < %s -passes=newgvn -newgvn-assumption=balanced -S | FileCheck %s --check-prefix=BAL
; RUN: opt < %s -passes=newgvn -newgvn-assumption=pessimistic -S | FileCheck %s --check-prefix=PESS

;; Cyclic phi equivalence: phi1 and phi2 in an irreducible cycle are equivalent
;; to %arg. Only optimistic discovers this (via iterative convergence).
;; Balanced and pessimistic do not (single-iteration).
define i32 @cyclic_phi(i32 %arg, i1 %cond) {
; OPT-LABEL: @cyclic_phi(
; OPT-NEXT:  bb:
; OPT-NEXT:    br i1 [[COND:%.*]], label [[BB2:%.*]], label [[BB1:%.*]]
; OPT:       bb1:
; OPT-NEXT:    br label [[BB2]]
; OPT:       bb2:
; OPT-NEXT:    br i1 [[COND]], label [[BB1]], label [[BB3:%.*]]
; OPT:       bb3:
; OPT-NEXT:    ret i32 0
;
; BAL-LABEL: @cyclic_phi(
; BAL-NEXT:  bb:
; BAL-NEXT:    br i1 [[COND:%.*]], label [[BB2:%.*]], label [[BB1:%.*]]
; BAL:       bb1:
; BAL-NEXT:    [[PHI1:%.*]] = phi i32 [ [[ARG:%.*]], [[BB:%.*]] ], [ [[PHI2:%.*]], [[BB2]] ]
; BAL-NEXT:    br label [[BB2]]
; BAL:       bb2:
; BAL-NEXT:    [[PHI2]] = phi i32 [ [[ARG]], [[BB]] ], [ [[PHI1]], [[BB1]] ]
; BAL-NEXT:    [[RESULT:%.*]] = sub i32 [[ARG]], [[PHI2]]
; BAL-NEXT:    br i1 [[COND]], label [[BB1]], label [[BB3:%.*]]
; BAL:       bb3:
; BAL-NEXT:    ret i32 [[RESULT]]
;
; PESS-LABEL: @cyclic_phi(
; PESS-NEXT:  bb:
; PESS-NEXT:    br i1 [[COND:%.*]], label [[BB2:%.*]], label [[BB1:%.*]]
; PESS:       bb1:
; PESS-NEXT:    [[PHI1:%.*]] = phi i32 [ [[ARG:%.*]], [[BB:%.*]] ], [ [[PHI2:%.*]], [[BB2]] ]
; PESS-NEXT:    br label [[BB2]]
; PESS:       bb2:
; PESS-NEXT:    [[PHI2]] = phi i32 [ [[ARG]], [[BB]] ], [ [[PHI1]], [[BB1]] ]
; PESS-NEXT:    [[RESULT:%.*]] = sub i32 [[ARG]], [[PHI2]]
; PESS-NEXT:    br i1 [[COND]], label [[BB1]], label [[BB3:%.*]]
; PESS:       bb3:
; PESS-NEXT:    ret i32 [[RESULT]]
;
bb:
  br i1 %cond, label %bb2, label %bb1
bb1:
  %phi1 = phi i32 [%arg, %bb], [%phi2, %bb2]
  br label %bb2
bb2:
  %phi2 = phi i32 [%arg, %bb], [%phi1, %bb1]
  %result = sub i32 %arg, %phi2
  br i1 %cond, label %bb1, label %bb3
bb3:
  ret i32 %result
}

;; Simple loop phi equivalence: m.0 and n.0 have the same initial value and
;; the same recurrence. Only optimistic discovers m.0 == n.0 (via iterative
;; convergence). Balanced and pessimistic do not (single-iteration).
define void @loop_phi_equiv(ptr %data) {
; OPT-LABEL: @loop_phi_equiv(
; OPT-NEXT:  bb:
; OPT-NEXT:    [[TMP:%.*]] = getelementptr inbounds i32, ptr [[DATA:%.*]], i64 3
; OPT-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP]], align 4
; OPT-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 4
; OPT-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
; OPT-NEXT:    br label [[LOOP:%.*]]
; OPT:       loop:
; OPT-NEXT:    [[M_0:%.*]] = phi i32 [ [[TMP3]], [[BB:%.*]] ], [ [[M_NEXT:%.*]], [[BODY:%.*]] ]
; OPT-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[BB]] ], [ [[I_NEXT:%.*]], [[BODY]] ]
; OPT-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[TMP1]]
; OPT-NEXT:    br i1 [[CMP]], label [[BODY]], label [[EXIT:%.*]]
; OPT:       body:
; OPT-NEXT:    store i32 0, ptr [[DATA]], align 4
; OPT-NEXT:    [[PTR1:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 1
; OPT-NEXT:    [[INC:%.*]] = load i32, ptr [[PTR1]], align 4
; OPT-NEXT:    [[M_NEXT]] = add nsw i32 [[M_0]], [[INC]]
; OPT-NEXT:    [[I_NEXT]] = add nsw i32 [[I_0]], 1
; OPT-NEXT:    br label [[LOOP]]
; OPT:       exit:
; OPT-NEXT:    ret void
;
; BAL-LABEL: @loop_phi_equiv(
; BAL-NEXT:  bb:
; BAL-NEXT:    [[TMP:%.*]] = getelementptr inbounds i32, ptr [[DATA:%.*]], i64 3
; BAL-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP]], align 4
; BAL-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 4
; BAL-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
; BAL-NEXT:    br label [[LOOP:%.*]]
; BAL:       loop:
; BAL-NEXT:    [[M_0:%.*]] = phi i32 [ [[TMP3]], [[BB:%.*]] ], [ [[M_NEXT:%.*]], [[BODY:%.*]] ]
; BAL-NEXT:    [[N_0:%.*]] = phi i32 [ [[TMP3]], [[BB]] ], [ [[N_NEXT:%.*]], [[BODY]] ]
; BAL-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[BB]] ], [ [[I_NEXT:%.*]], [[BODY]] ]
; BAL-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[TMP1]]
; BAL-NEXT:    br i1 [[CMP]], label [[BODY]], label [[EXIT:%.*]]
; BAL:       body:
; BAL-NEXT:    [[DIFF:%.*]] = sub nsw i32 [[M_0]], [[N_0]]
; BAL-NEXT:    store i32 [[DIFF]], ptr [[DATA]], align 4
; BAL-NEXT:    [[PTR1:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 1
; BAL-NEXT:    [[INC:%.*]] = load i32, ptr [[PTR1]], align 4
; BAL-NEXT:    [[M_NEXT]] = add nsw i32 [[M_0]], [[INC]]
; BAL-NEXT:    [[N_NEXT]] = add nsw i32 [[N_0]], [[INC]]
; BAL-NEXT:    [[I_NEXT]] = add nsw i32 [[I_0]], 1
; BAL-NEXT:    br label [[LOOP]]
; BAL:       exit:
; BAL-NEXT:    ret void
;
; PESS-LABEL: @loop_phi_equiv(
; PESS-NEXT:  bb:
; PESS-NEXT:    [[TMP:%.*]] = getelementptr inbounds i32, ptr [[DATA:%.*]], i64 3
; PESS-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP]], align 4
; PESS-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 4
; PESS-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP2]], align 4
; PESS-NEXT:    br label [[LOOP:%.*]]
; PESS:       loop:
; PESS-NEXT:    [[M_0:%.*]] = phi i32 [ [[TMP3]], [[BB:%.*]] ], [ [[M_NEXT:%.*]], [[BODY:%.*]] ]
; PESS-NEXT:    [[N_0:%.*]] = phi i32 [ [[TMP3]], [[BB]] ], [ [[N_NEXT:%.*]], [[BODY]] ]
; PESS-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[BB]] ], [ [[I_NEXT:%.*]], [[BODY]] ]
; PESS-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[TMP1]]
; PESS-NEXT:    br i1 [[CMP]], label [[BODY]], label [[EXIT:%.*]]
; PESS:       body:
; PESS-NEXT:    [[DIFF:%.*]] = sub nsw i32 [[M_0]], [[N_0]]
; PESS-NEXT:    store i32 [[DIFF]], ptr [[DATA]], align 4
; PESS-NEXT:    [[PTR1:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 1
; PESS-NEXT:    [[INC:%.*]] = load i32, ptr [[PTR1]], align 4
; PESS-NEXT:    [[M_NEXT]] = add nsw i32 [[M_0]], [[INC]]
; PESS-NEXT:    [[N_NEXT]] = add nsw i32 [[N_0]], [[INC]]
; PESS-NEXT:    [[I_NEXT]] = add nsw i32 [[I_0]], 1
; PESS-NEXT:    br label [[LOOP]]
; PESS:       exit:
; PESS-NEXT:    ret void
;
bb:
  %tmp = getelementptr inbounds i32, ptr %data, i64 3
  %tmp1 = load i32, ptr %tmp, align 4
  %tmp2 = getelementptr inbounds i32, ptr %data, i64 4
  %tmp3 = load i32, ptr %tmp2, align 4
  br label %loop

loop:
  %m.0 = phi i32 [ %tmp3, %bb ], [ %m.next, %latch ]
  %n.0 = phi i32 [ %tmp3, %bb ], [ %n.next, %latch ]
  %i.0 = phi i32 [ 0, %bb ], [ %i.next, %latch ]
  %cmp = icmp slt i32 %i.0, %tmp1
  br i1 %cmp, label %body, label %exit

body:
  %diff = sub nsw i32 %m.0, %n.0
  store i32 %diff, ptr %data, align 4
  %ptr1 = getelementptr inbounds i32, ptr %data, i64 1
  %inc = load i32, ptr %ptr1, align 4
  %m.next = add nsw i32 %m.0, %inc
  %n.next = add nsw i32 %n.0, %inc
  br label %latch

latch:
  %i.next = add nsw i32 %i.0, 1
  br label %loop

exit:
  ret void
}
