; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -enable-phi-of-ops=true -S | FileCheck %s
; XFAIL: *

; Since %x and %z are known to be equivalent,
; the predicate info that applies to %x also applies to %z.
define i32 @foo(i32 %a) {
; CHECK-LABEL: define i32 @foo(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:    [[X:%.*]] = add i32 [[A]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    ret i32 10
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret i32 poison
;
  %x = add i32 %a, 1
  %cmp = icmp eq i32 %x, 10
  br i1 %cmp, label %bb1, label %bb2
bb1:
  %z = add i32 %a, 1
  ret i32 %z
bb2:
  ret i32 poison
}
