; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -enable-phi-of-ops=true -enable-newgvn-pre=true -S | FileCheck %s
@global = external global ptr

define void @widget(i1 %arg) {
; CHECK-LABEL: define void @widget(
; CHECK-SAME: i1 [[ARG:%.*]]) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[LOAD_PRE:%.*]] = load ptr, ptr @global, align 8
; CHECK-NEXT:    br label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi ptr [ [[LOAD_PRE]], %[[BB]] ], [ [[PHIOFOPS1:%.*]], %[[BB7:.*]] ]
; CHECK-NEXT:    br i1 [[ARG]], label %[[BB3:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    tail call void null()
; CHECK-NEXT:    [[LOAD4_PRE:%.*]] = load ptr, ptr @global, align 8
; CHECK-NEXT:    br label %[[BB3]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[PHIOFOPS2:%.*]] = phi ptr [ [[PHIOFOPS]], %[[BB1]] ], [ [[LOAD4_PRE]], %[[BB2]] ]
; CHECK-NEXT:    br i1 [[ARG]], label %[[BB7]], label %[[BB6:.*]]
; CHECK:       [[BB6]]:
; CHECK-NEXT:    [[CALL:%.*]] = tail call i64 null(i32 0, ptr null, i64 0)
; CHECK-NEXT:    [[LOAD8_PRE:%.*]] = load ptr, ptr @global, align 8
; CHECK-NEXT:    br label %[[BB7]]
; CHECK:       [[BB7]]:
; CHECK-NEXT:    [[PHIOFOPS1]] = phi ptr [ [[PHIOFOPS2]], %[[BB3]] ], [ [[LOAD8_PRE]], %[[BB6]] ]
; CHECK-NEXT:    br label %[[BB1]]
;
bb:
  br label %bb1

bb1:                                              ; preds = %bb7, %bb
  %load = load ptr, ptr @global, align 8
  %getelementptr = getelementptr i8, ptr %load, i64 2056
  br i1 %arg, label %bb3, label %bb2

bb2:                                              ; preds = %bb1
  tail call void null()
  br label %bb3

bb3:                                              ; preds = %bb2, %bb1
  %load4 = load ptr, ptr @global, align 8
  %getelementptr5 = getelementptr i8, ptr %load4, i64 2052
  br i1 %arg, label %bb7, label %bb6

bb6:                                              ; preds = %bb3
  %call = tail call i64 null(i32 0, ptr null, i64 0)
  br label %bb7

bb7:                                              ; preds = %bb6, %bb3
  %load8 = load ptr, ptr @global, align 8
  %getelementptr9 = getelementptr i8, ptr %load8, i64 2080
  br label %bb1
}
