; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
;
; When the memset destination involves a non-constant GEP index (e.g.,
; sext i32 0), GetPointerBaseWithConstantOffset fails on the raw pointer.
; NewGVN's leader lookup simplifies the GEP, exposing the constant offset
; relationship and enabling load coercion from the memset.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.T = type { i64, i64, i64 }

@G = external global [16384 x %struct.T]

declare void @llvm.memset.p0.i64(ptr writeonly captures(none), i8, i64, i1 immarg)

; The sext i32 0 prevents GetPointerBaseWithConstantOffset from decomposing
; the memset destination.  NewGVN's leader lookup resolves it to @G, allowing
; the load at offset 16 to be forwarded from the memset as 0.
define void @memset_sext_gep(ptr %out, i1 %cond) {
; CHECK-LABEL: @memset_sext_gep(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr @G, i8 0, i64 24, i1 false)
; CHECK-NEXT:    br i1 [[COND:%.*]], label [[IF_THEN:%.*]], label [[JOIN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    store i64 0, ptr getelementptr inbounds nuw (i8, ptr @G, i64 16), align 8
; CHECK-NEXT:    br label [[JOIN]]
; CHECK:       join:
; CHECK-NEXT:    store i64 0, ptr [[OUT:%.*]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %ext = sext i32 0 to i64
  %base = getelementptr [16384 x %struct.T], ptr @G, i64 %ext
  call void @llvm.memset.p0.i64(ptr %base, i8 0, i64 24, i1 false)
  %p16 = getelementptr i8, ptr %base, i64 16
  br i1 %cond, label %if.then, label %join

if.then:
  store i64 0, ptr %p16, align 8
  br label %join

join:
  %v = load i64, ptr %p16, align 8
  store i64 %v, ptr %out, align 8
  ret void
}
