; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=newgvn -S %s | FileCheck %s
;
; Verify that NewGVN does not crash with a verifyIterationSettled assertion
; when a load's phi-of-ops depends on a MemoryPhi whose congruence class
; changes after the phi-of-ops is created.
;
; The first test has stores/loads through null; the second through an alloca
; in a loop.

%struct._reg_trie_trans = type { i32, i32 }

; Bug 1: MemoryPhi class changes after phi-of-ops created for a load.
; The load in if.end3011 creates a phi-of-ops by looking through MemoryPhi4,
; which is initially congruent to MemoryDef1. When the back-edge is processed,
; MemoryPhi4 changes class, but the load was not reprocessed.
define fastcc i32 @memoryphi_class_change(ptr %call2926, i1 %cmp2999) {
; CHECK-LABEL: define fastcc i32 @memoryphi_class_change(
; CHECK-SAME: ptr [[CALL2926:%.*]], i1 [[CMP2999:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    store ptr [[CALL2926]], ptr null, align 8
; CHECK-NEXT:    br label %[[FOR_BODY2934:.*]]
; CHECK:       [[FOR_BODY2934]]:
; CHECK-NEXT:    [[DOTPRE_PRE_PHI:%.*]] = phi ptr [ [[DOTPRE_PHI:%.*]], %[[IF_END3011:.*]] ], [ [[CALL2926]], %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[CMP2999]], label %[[IF_THEN3001:.*]], label %[[FOR_BODY2934_IF_END3011_CRIT_EDGE:.*]]
; CHECK:       [[FOR_BODY2934_IF_END3011_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[IF_END3011]]
; CHECK:       [[IF_THEN3001]]:
; CHECK-NEXT:    store ptr null, ptr null, align 8
; CHECK-NEXT:    br label %[[IF_END3011]]
; CHECK:       [[IF_END3011]]:
; CHECK-NEXT:    [[DOTPRE_PHI]] = phi ptr [ null, %[[IF_THEN3001]] ], [ [[DOTPRE_PRE_PHI]], %[[FOR_BODY2934_IF_END3011_CRIT_EDGE]] ]
; CHECK-NEXT:    br label %[[FOR_BODY2934]]
;
entry:
  store ptr %call2926, ptr null, align 8
  br label %for.body2934

for.body2934:
  br i1 %cmp2999, label %if.then3001, label %if.end3011

if.then3001:
  store ptr null, ptr null, align 8
  br label %if.end3011

if.end3011:
  %0 = load ptr, ptr null, align 8
  %arrayidx3028 = getelementptr %struct._reg_trie_trans, ptr %0, i64 0
  br label %for.body2934
}

; Bug 2: Load's phi-of-ops leader appears after another load changes class.
; Load %2 in if.end900 tries to create a phi-of-ops but fails because load %1
; hasn't been numbered to a LoadExpression yet. When load %1 later changes
; class, load %2 was not reprocessed.
define fastcc ptr @phiofops_leader_appears_later(i1 %cond, i1 %cmp882, ptr %0) {
; CHECK-LABEL: define fastcc ptr @phiofops_leader_appears_later(
; CHECK-SAME: i1 [[COND:%.*]], i1 [[CMP882:%.*]], ptr [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TYPE:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr null, ptr [[TYPE]], align 8
; CHECK-NEXT:    br label %[[WHILE_COND:.*]]
; CHECK:       [[WHILE_COND]]:
; CHECK-NEXT:    [[DOTPRE_PRE_PHI:%.*]] = phi ptr [ null, %[[SW_BB447:.*]] ], [ null, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[COND]], label %[[SW_BB447]], label %[[SW_BB858:.*]]
; CHECK:       [[SW_BB858]]:
; CHECK-NEXT:    br i1 [[CMP882]], label %[[IF_ELSE887:.*]], label %[[SW_BB858_IF_END889_CRIT_EDGE:.*]]
; CHECK:       [[SW_BB858_IF_END889_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[IF_END889:.*]]
; CHECK:       [[SW_BB447]]:
; CHECK-NEXT:    store i32 0, ptr null, align 4
; CHECK-NEXT:    store ptr null, ptr [[TYPE]], align 8
; CHECK-NEXT:    br label %[[WHILE_COND]]
; CHECK:       [[IF_ELSE887]]:
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[TYPE]], align 8
; CHECK-NEXT:    br label %[[IF_END889]]
; CHECK:       [[IF_END889]]:
; CHECK-NEXT:    [[DOTPRE_PHI:%.*]] = phi ptr [ [[TMP0]], %[[IF_ELSE887]] ], [ [[DOTPRE_PRE_PHI]], %[[SW_BB858_IF_END889_CRIT_EDGE]] ]
; CHECK-NEXT:    br i1 [[CMP882]], label %[[IF_ELSE898:.*]], label %[[IF_END900:.*]]
; CHECK:       [[IF_ELSE898]]:
; CHECK-NEXT:    store ptr null, ptr [[TYPE]], align 8
; CHECK-NEXT:    br label %[[IF_END900]]
; CHECK:       [[IF_END900]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[DOTPRE_PHI]], %[[IF_END889]] ], [ null, %[[IF_ELSE898]] ]
; CHECK-NEXT:    ret ptr [[TMP2]]
;
entry:
  %type = alloca ptr, align 8
  store ptr null, ptr %type, align 8
  br label %while.cond

while.cond:
  br i1 %cond, label %sw.bb447, label %sw.bb858

sw.bb858:
  br i1 %cmp882, label %if.else887, label %if.end889

sw.bb447:
  store i32 0, ptr null, align 4
  store ptr null, ptr %type, align 8
  br label %while.cond

if.else887:
  store ptr %0, ptr %type, align 8
  br label %if.end889

if.end889:
  %1 = load ptr, ptr %type, align 8
  %bf.load8905 = load i64, ptr %1, align 8
  br i1 %cmp882, label %if.else898, label %if.end900

if.else898:
  store ptr null, ptr %type, align 8
  br label %if.end900

if.end900:
  %2 = load ptr, ptr %type, align 8
  ret ptr %2
}
