; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
target datalayout = "E-m:e-i64:64-n32:64"

@global = external hidden unnamed_addr constant [11 x i8], align 1
;; Ensure we do not believe the indexing increments are unreachable due to incorrect memory
;; equivalence detection.  In PR31483, we were deleting those blocks as unreachable
; Function Attrs: nounwind
define signext i32 @ham(ptr %arg, ptr %arg1) {
; CHECK-LABEL: @ham(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[ALLOC:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[ARG1:%.*]], ptr [[ALLOC]], align 8
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[PRE_PHI:%.*]] = phi ptr [ [[PRE_PRE_PHI:%.*]], [[BB22:%.*]] ], [ [[ARG1]], [[BB:%.*]] ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[ARG:%.*]], [[BB]] ], [ [[NEXT:%.*]], [[BB22]] ]
; CHECK-NEXT:    [[CH:%.*]] = load i8, ptr [[PTR]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i8 [[CH]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[BB6:%.*]], label [[BB23:%.*]]
; CHECK:       bb6:
; CHECK-NEXT:    [[NEXT]] = getelementptr inbounds i8, ptr [[PTR]], i32 1
; CHECK-NEXT:    [[EXT:%.*]] = zext i8 [[CH]] to i32
; CHECK-NEXT:    switch i32 [[EXT]], label [[BB22]] [
; CHECK-NEXT:      i32 115, label [[BB10:%.*]]
; CHECK-NEXT:      i32 105, label [[BB16:%.*]]
; CHECK-NEXT:      i32 99, label [[BB16]]
; CHECK-NEXT:    ]
; CHECK:       bb10:
; CHECK-NEXT:    [[P12:%.*]] = getelementptr inbounds i8, ptr [[PRE_PHI]], i64 8
; CHECK-NEXT:    store ptr [[P12]], ptr [[ALLOC]], align 8
; CHECK-NEXT:    [[P14:%.*]] = load ptr, ptr [[PRE_PHI]], align 8
; CHECK-NEXT:    {{.*}} = call signext i32 (ptr, ...) @zot(ptr @global, ptr [[P14]])
; CHECK-NEXT:    br label [[BB22]]
; CHECK:       bb16:
; CHECK-NEXT:    [[P17:%.*]] = load ptr, ptr [[ALLOC]], align 8
; CHECK-NEXT:    [[P18:%.*]] = getelementptr inbounds i8, ptr [[P17]], i64 8
; CHECK-NEXT:    store ptr [[P18]], ptr [[ALLOC]], align 8
; CHECK-NEXT:    {{.*}} = getelementptr inbounds i8, ptr [[P17]], i64 4
; CHECK-NEXT:    br label [[BB22]]
; CHECK:       bb22:
; CHECK-NEXT:    [[PRE_PRE_PHI]] = phi ptr [ [[P18]], [[BB16]] ], [ [[P12]], [[BB10]] ], [ [[PRE_PHI]], [[BB6]] ]
; CHECK-NEXT:    br label [[BB2]]
; CHECK:       bb23:
; CHECK-NEXT:    call void @llvm.va_end.p0(ptr [[ALLOC]])
; CHECK-NEXT:    ret i32 undef
;
bb:
  %tmp = alloca ptr, align 8
  store ptr %arg1, ptr %tmp, align 8
  br label %bb2

bb2:                                              ; preds = %bb22, %bb
  %tmp3 = phi ptr [ %arg, %bb ], [ %tmp7, %bb22 ]
  %tmp4 = load i8, ptr %tmp3, align 1
  %tmp5 = icmp ne i8 %tmp4, 0
  br i1 %tmp5, label %bb6, label %bb23

bb6:                                              ; preds = %bb2
  %tmp7 = getelementptr inbounds i8, ptr %tmp3, i32 1
  %tmp8 = load i8, ptr %tmp3, align 1
  %tmp9 = zext i8 %tmp8 to i32
  switch i32 %tmp9, label %bb22 [
  i32 115, label %bb10
  i32 105, label %bb16
  i32 99, label %bb16
  ]

bb10:                                             ; preds = %bb6
  %tmp11 = load ptr, ptr %tmp, align 8
  %tmp12 = getelementptr inbounds i8, ptr %tmp11, i64 8
  store ptr %tmp12, ptr %tmp, align 8
  %tmp14 = load ptr, ptr %tmp11, align 8
  %tmp15 = call signext i32 (ptr, ...) @zot(ptr @global, ptr %tmp14)
  br label %bb22

bb16:                                             ; preds = %bb6, %bb6
  %tmp17 = load ptr, ptr %tmp, align 8
  %tmp18 = getelementptr inbounds i8, ptr %tmp17, i64 8
  store ptr %tmp18, ptr %tmp, align 8
  %tmp19 = getelementptr inbounds i8, ptr %tmp17, i64 4
  %tmp21 = load i32, ptr %tmp19, align 4
  br label %bb22

bb22:                                             ; preds = %bb16, %bb10, %bb6
  br label %bb2

bb23:                                             ; preds = %bb2
  call void @llvm.va_end(ptr %tmp)
  ret i32 undef
}

declare signext i32 @zot(ptr, ...)

; Function Attrs: nounwind
declare void @llvm.va_end(ptr)
