; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=newgvn %s | FileCheck %s

@a = external global i32

define void @b(i1 %arg) {
; CHECK-LABEL: @b(
; CHECK-NEXT:    br i1 false, label [[C:%.*]], label [[WHILE_D:%.*]]
; CHECK:       .while.d_crit_edge:
; CHECK-NEXT:    br label [[WHILE_D1:%.*]]
; CHECK:       .c_crit_edge:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label [[C1:%.*]]
; CHECK:       while.d:
; CHECK-NEXT:    br label [[F:%.*]]
; CHECK:       f:
; CHECK-NEXT:    br i1 [[ARG:%.*]], label [[F_IF_E_CRIT_EDGE:%.*]], label [[F_C_CRIT_EDGE:%.*]]
; CHECK:       f.c_crit_edge:
; CHECK-NEXT:    br label [[C1]]
; CHECK:       f.if.e_crit_edge:
; CHECK-NEXT:    br label [[IF_E:%.*]]
; CHECK:       c:
; CHECK-NEXT:    br i1 [[ARG]], label [[IF_G:%.*]], label [[C_IF_E_CRIT_EDGE:%.*]]
; CHECK:       c.if.e_crit_edge:
; CHECK-NEXT:    br label [[IF_E]]
; CHECK:       if.g:
; CHECK-NEXT:    store i32 undef, ptr @a, align 4
; CHECK-NEXT:    br label [[WHILE_D1]]
; CHECK:       if.e:
; CHECK-NEXT:    br label [[F]]
;
  br i1 false, label %c, label %while.d

while.d:                                          ; preds = %if.g, %0
  br label %f

f:                                                ; preds = %if.e, %while.d
  br i1 %arg, label %if.e, label %c

c:                                                ; preds = %f, %0
  br i1 %arg, label %if.g, label %if.e

if.g:                                             ; preds = %c
  store i32 undef, ptr @a
  br label %while.d

if.e:                                             ; preds = %c, %f
  br label %f
}

