; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true -S < %s | FileCheck %s
;
; Verify that load PRE with GEP rematerialization does not crash when
; splitting a critical edge from the unavailable predecessor.  The PHI
; operands of the GEP must be translated using the split block (InsertBB),
; not the original UnavailPred, because SplitCriticalEdge updates the
; PHI's incoming blocks.

define fastcc ptr @test(ptr %p, i32 %sel) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    switch i32 [[SEL:%.*]], label [[LOOP_HEADER]] [
; CHECK-NEXT:      i32 23, label [[MERGE:%.*]]
; CHECK-NEXT:      i32 25, label [[MERGE]]
; CHECK-NEXT:    ]
; CHECK:       merge:
; CHECK-NEXT:    br i1 true, label [[MERGE_INNER_HEADER_CRIT_EDGE:%.*]], label [[BACKEDGE:%.*]]
; CHECK:       merge.inner.header_crit_edge:
; CHECK-NEXT:    [[GEP_PHI_TRANS_INSERT:%.*]] = getelementptr i8, ptr null, i64 24
; CHECK-NEXT:    [[LOAD_PRE:%.*]] = load ptr, ptr [[GEP_PHI_TRANS_INSERT]], align 8
; CHECK-NEXT:    br label [[INNER_HEADER:%.*]]
; CHECK:       backedge:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label [[LOOP_HEADER]]
; CHECK:       inner.header:
; CHECK-NEXT:    [[LOAD_PRE_PHI:%.*]] = phi ptr [ [[PHI:%.*]], [[INNER_LATCH:%.*]] ], [ [[LOAD_PRE]], [[MERGE_INNER_HEADER_CRIT_EDGE]] ]
; CHECK-NEXT:    [[PHI]] = phi ptr [ null, [[MERGE_INNER_HEADER_CRIT_EDGE]] ], [ [[LOAD_PRE_PHI]], [[INNER_LATCH]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[PHI]], i64 24
; CHECK-NEXT:    br label [[INNER_LATCH]]
; CHECK:       inner.latch:
; CHECK-NEXT:    br i1 true, label [[INNER_HEADER]], label [[INNER_BODY:%.*]]
; CHECK:       inner.body:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label [[INNER_LATCH]]
;
entry:
  br label %loop.header

loop.header:
  switch i32 %sel, label %loop.header [
  i32 23, label %merge
  i32 25, label %merge
  ]

merge:
  br i1 true, label %inner.header, label %backedge

backedge:
  br label %loop.header

inner.header:
  %phi = phi ptr [ null, %merge ], [ %load, %inner.latch ]
  %gep = getelementptr i8, ptr %phi, i64 24
  %load = load ptr, ptr %gep, align 8
  br label %inner.latch

inner.latch:
  br i1 true, label %inner.header, label %inner.body

inner.body:
  store ptr null, ptr %p, align 8
  br label %inner.latch
}
