; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=optpre -S %s | FileCheck %s

@a = common global i32 0, align 4
@.str = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1
define i32 @main() #0 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @a, align 4
; CHECK-NEXT:    [[NEG:%.*]] = xor i32 [[TMP0]], -1
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP0]], -1
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ [[TMP0]], [[ENTRY:%.*]] ], [ [[NEG]], [[IF_THEN]] ]
; CHECK-NEXT:    [[STOREMERGE:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN]] ], [ [[NEG]], [[ENTRY]] ]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp ult i32 [[STOREMERGE]], [[PHIOFOPS]]
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF_THEN3:%.*]], label [[IF_END6:%.*]]
; CHECK:       if.then3:
; CHECK-NEXT:    br i1 false, label [[LOR_RHS:%.*]], label [[LOR_END:%.*]]
; CHECK:       lor.rhs:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label [[LOR_END]]
; CHECK:       lor.end:
; CHECK-NEXT:    store i32 1, ptr @a, align 4
; CHECK-NEXT:    br label [[IF_END6]]
; CHECK:       if.end6:
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @a, align 4
; CHECK-NEXT:    [[CALL:%.*]] = call i32 (ptr, ...) @printf(ptr @.str, i32 [[TMP2]])
; CHECK-NEXT:    ret i32 0
;
entry:
  %0 = load i32, ptr @a, align 4
  %neg = xor i32 %0, -1
  %cmp = icmp sgt i32 %0, -1
  br i1 %cmp, label %if.then, label %if.end

if.then:
  br label %if.end

if.end:
  %storemerge = phi i32 [ %0, %if.then ], [ %neg, %entry ]
  %neg1 = xor i32 %storemerge, -1
  %cmp2 = icmp ult i32 %storemerge, %neg1
  br i1 %cmp2, label %if.then3, label %if.end6

if.then3:
  %tobool = icmp eq i32 %storemerge, -1
  br i1 %tobool, label %lor.rhs, label %lor.end

lor.rhs:
  %tobool5 = icmp ne i32 %0, 0
  %phitmp = zext i1 %tobool5 to i32
  br label %lor.end

lor.end:
  %1 = phi i32 [ 1, %if.then3 ], [ %phitmp, %lor.rhs ]
  store i32 %1, ptr @a, align 4
  br label %if.end6

if.end6:
  %2 = load i32, ptr @a, align 4
  %call = call i32 (ptr, ...) @printf(ptr @.str, i32 %2) #3
  ret i32 0
}
declare i32 @printf(ptr, ...) #2
