; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S < %s -passes=optpre | FileCheck %s

@a = external global i64

define void @fn1(i1 %bc) {
; CHECK-LABEL: define void @fn1(
; CHECK-SAME: i1 [[BC:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[LV:%.*]] = load i32, ptr @a, align 4
; CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[LV]], -131072
; CHECK-NEXT:    [[BF_SET:%.*]] = or i32 1, [[BF_CLEAR]]
; CHECK-NEXT:    [[BF_CLEAR_1:%.*]] = and i32 [[BF_SET]], -131072
; CHECK-NEXT:    [[BF_SET_1:%.*]] = or i32 1, [[BF_CLEAR_1]]
; CHECK-NEXT:    br i1 [[BC]], label [[FOR_COND]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    store i32 [[BF_SET_1]], ptr @a, align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.cond1.1, %entry
  %tmp = phi i1 [ undef, %entry ], [ 1, %for.cond ]
  %conv = zext i1 %tmp to i32
  %lv = load i32, ptr @a
  %bf.clear = and i32 %lv, -131072
  %bf.set = or i32 %conv, %bf.clear
  %bf.clear.1 = and i32 %bf.set, -131072
  %bf.set.1 = or i32 1, %bf.clear.1
  br i1 %bc, label %for.cond, label %exit

exit:                              ; preds = %for.cond1
  store i32 %bf.set.1, ptr @a
  ret void
}
