; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true < %s | FileCheck %s

; Point-sensitive capture: GVN's memdep uses PointerMayBeCapturedBefore to
; determine that an alloca isn't captured at a given call site, allowing it
; to see through the call. MSSA uses whole-function capture analysis, so
; NewGVN conservatively treats the call as a clobber.

; %hden is stored in entry, then neg_double is called with %hnum (NOT %hden).
; The load of %hden after the call should be replaced with %hden_orig.
define i64 @capture_single_path(i64 %hnum_orig, i64 %hden_orig) {
; CHECK-LABEL: define i64 @capture_single_path(
; CHECK-SAME: i64 [[HNUM_ORIG:%.*]], i64 [[HDEN_ORIG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[HNUM:%.*]] = alloca i64, align 8
; CHECK-NEXT:    [[HDEN:%.*]] = alloca i64, align 8
; CHECK-NEXT:    store i64 [[HNUM_ORIG]], ptr [[HNUM]], align 8
; CHECK-NEXT:    store i64 [[HDEN_ORIG]], ptr [[HDEN]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[HNUM_ORIG]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @neg_double(i64 [[HNUM_ORIG]], i64 0, ptr [[HNUM]], ptr [[HNUM]])
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[CALL2:%.*]] = call i32 @neg_double(i64 [[HDEN_ORIG]], i64 0, ptr [[HDEN]], ptr [[HDEN]])
; CHECK-NEXT:    [[V2:%.*]] = load i64, ptr [[HDEN]], align 8
; CHECK-NEXT:    ret i64 [[V2]]
;
entry:
  %hnum = alloca i64, align 8
  %hden = alloca i64, align 8
  store i64 %hnum_orig, ptr %hnum, align 8
  store i64 %hden_orig, ptr %hden, align 8
  %cmp = icmp slt i64 %hnum_orig, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:
  %call = call i32 @neg_double(i64 %hnum_orig, i64 0, ptr %hnum, ptr %hnum)
  br label %if.end

if.end:
  ; neg_double at if.then only captures %hnum, not %hden.
  ; %hden is captured later by call2, but not yet — load should be %hden_orig.
  %v = load i64, ptr %hden, align 8
  %call2 = call i32 @neg_double(i64 %v, i64 0, ptr %hden, ptr %hden)
  %v2 = load i64, ptr %hden, align 8
  ret i64 %v2
}

; Diamond store to %lden, then neg_double called with %hnum (NOT %lden).
; The load of %lden after the call should be a PHI of the two stored values.
define i64 @capture_diamond_store(i64 %lden_orig, i64 %hnum_orig) {
; CHECK-LABEL: define i64 @capture_diamond_store(
; CHECK-SAME: i64 [[LDEN_ORIG:%.*]], i64 [[HNUM_ORIG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[LDEN:%.*]] = alloca i64, align 8
; CHECK-NEXT:    [[HNUM:%.*]] = alloca i64, align 8
; CHECK-NEXT:    store i64 [[LDEN_ORIG]], ptr [[LDEN]], align 8
; CHECK-NEXT:    store i64 [[HNUM_ORIG]], ptr [[HNUM]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i64 [[LDEN_ORIG]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[OVERRIDE:.*]], label %[[JOIN:.*]]
; CHECK:       [[OVERRIDE]]:
; CHECK-NEXT:    store i64 1, ptr [[LDEN]], align 8
; CHECK-NEXT:    br label %[[JOIN]]
; CHECK:       [[JOIN]]:
; CHECK-NEXT:    [[V:%.*]] = phi i64 [ [[LDEN_ORIG]], %[[ENTRY]] ], [ 1, %[[OVERRIDE]] ]
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @neg_double(i64 [[HNUM_ORIG]], i64 0, ptr [[HNUM]], ptr [[HNUM]])
; CHECK-NEXT:    [[CALL2:%.*]] = call i32 @neg_double(i64 [[V]], i64 0, ptr [[LDEN]], ptr [[LDEN]])
; CHECK-NEXT:    [[V2:%.*]] = load i64, ptr [[LDEN]], align 8
; CHECK-NEXT:    ret i64 [[V2]]
;
entry:
  %lden = alloca i64, align 8
  %hnum = alloca i64, align 8
  store i64 %lden_orig, ptr %lden, align 8
  store i64 %hnum_orig, ptr %hnum, align 8
  %cond = icmp eq i64 %lden_orig, 0
  br i1 %cond, label %override, label %join

override:
  store i64 1, ptr %lden, align 8
  br label %join

join:
  ; neg_double only captures %hnum, not %lden.
  ; %lden is captured later by call2, but not yet — load should be PHI.
  %call = call i32 @neg_double(i64 %hnum_orig, i64 0, ptr %hnum, ptr %hnum)
  %v = load i64, ptr %lden, align 8
  %call2 = call i32 @neg_double(i64 %v, i64 0, ptr %lden, ptr %lden)
  %v2 = load i64, ptr %lden, align 8
  ret i64 %v2
}

declare i32 @neg_double(i64, i64, ptr, ptr)
