; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true < %s | FileCheck %s
; Cascading PRE: loop header load where only one path through the loop body
; clobbers the loaded pointer.  Two rounds of PRE:
;  1) PRE of the header load — inserts reload in latch, PHI in header.
;  2) PRE of the latch reload — inserts reload in clobber_path, PHI in latch.


define i64 @conditional_clobber(ptr %p, i64 %init, i1 %flag) {
; CHECK-LABEL: define i64 @conditional_clobber(
; CHECK-SAME: ptr [[P:%.*]], i64 [[INIT:%.*]], i1 [[FLAG:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    store i64 [[INIT]], ptr [[P]], align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[V_PRE_PHI:%.*]] = phi i64 [ [[V_PRE_PRE_PHI:%.*]], %[[LATCH:.*]] ], [ [[INIT]], %[[ENTRY]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[V_PRE_PHI]], 0
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[BODY:.*]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    br i1 [[FLAG]], label %[[CLOBBER_PATH:.*]], label %[[NOCLOBBER:.*]]
; CHECK:       [[CLOBBER_PATH]]:
; CHECK-NEXT:    call void @may_write(ptr [[P]])
; CHECK-NEXT:    [[V_PRE_PRE:%.*]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[NOCLOBBER]]:
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[V_PRE_PRE_PHI]] = phi i64 [ [[V_PRE_PHI]], %[[NOCLOBBER]] ], [ [[V_PRE_PRE]], %[[CLOBBER_PATH]] ]
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  store i64 %init, ptr %p
  br label %loop

loop:
  %v = load i64, ptr %p
  %done = icmp eq i64 %v, 0
  br i1 %done, label %exit, label %body

body:
  br i1 %flag, label %clobber_path, label %noclobber

clobber_path:
  call void @may_write(ptr %p)
  br label %latch

noclobber:
  br label %latch

latch:
  br label %loop

exit:
  ret i64 %v
}

declare void @may_write(ptr)
