; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true < %s | FileCheck %s
; Cascading PRE across two consecutive loops loading from the same pointer.


define i64 @two_loops(ptr %p, i64 %init) {
; CHECK-LABEL: define i64 @two_loops(
; CHECK-SAME: ptr [[P:%.*]], i64 [[INIT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    store i64 [[INIT]], ptr [[P]], align 4
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[V1_PRE_PHI:%.*]] = phi i64 [ [[V1_PRE:%.*]], %[[BODY1:.*]] ], [ [[INIT]], %[[ENTRY]] ]
; CHECK-NEXT:    [[DONE1:%.*]] = icmp eq i64 [[V1_PRE_PHI]], 0
; CHECK-NEXT:    br i1 [[DONE1]], label %[[BETWEEN:.*]], label %[[BODY1]]
; CHECK:       [[BODY1]]:
; CHECK-NEXT:    call void @may_write(ptr [[P]])
; CHECK-NEXT:    [[V1_PRE]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[LOOP1]]
; CHECK:       [[BETWEEN]]:
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[V2_PRE_PHI:%.*]] = phi i64 [ [[V2_PRE:%.*]], %[[BODY2:.*]] ], [ [[V1_PRE_PHI]], %[[BETWEEN]] ]
; CHECK-NEXT:    [[DONE2:%.*]] = icmp eq i64 [[V2_PRE_PHI]], 0
; CHECK-NEXT:    br i1 [[DONE2]], label %[[EXIT:.*]], label %[[BODY2]]
; CHECK:       [[BODY2]]:
; CHECK-NEXT:    call void @may_write(ptr [[P]])
; CHECK-NEXT:    [[V2_PRE]] = load i64, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[LOOP2]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  store i64 %init, ptr %p
  br label %loop1

loop1:
  %v1 = load i64, ptr %p
  %done1 = icmp eq i64 %v1, 0
  br i1 %done1, label %between, label %body1

body1:
  call void @may_write(ptr %p)
  br label %loop1

between:
  br label %loop2

loop2:
  %v2 = load i64, ptr %p
  %done2 = icmp eq i64 %v2, 0
  br i1 %done2, label %exit, label %body2

body2:
  call void @may_write(ptr %p)
  br label %loop2

exit:
  ret i64 %v2
}

declare void @may_write(ptr)
