; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true < %s | FileCheck %s

; Two patterns block NewGVN's load PRE that GVN handles:
;
; 1. liveOnEntry clobber: when the per-predecessor MSSA walker returns
;    liveOnEntry, the PRE code can't extract an available value (no store
;    or load to read from). GVN's memdep finds the earlier load because
;    it directly tracks non-local deps.
;
; 2. Single-predecessor PRE: NewGVN's performPRE skips blocks with < 2
;    predecessors. GVN's memdep traces backward through single-pred
;    chains to the effective merge point.

;--- Pattern 1: liveOnEntry clobber in a 2-predecessor merge ---

; Entry loads %p, then diamond: call_arm clobbers, skip_arm doesn't.
; At merge, the load should be PRE'd: %v0 on skip_arm, fresh load on call_arm.
define i64 @diamond_load_entry(ptr %p) {
; CHECK-LABEL: define i64 @diamond_load_entry(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[V0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[CALL_ARM:.*]], label %[[SKIP_ARM:.*]]
; CHECK:       [[CALL_ARM]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[V1_PRE:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[SKIP_ARM]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V1:%.*]] = phi i64 [ [[V0]], %[[SKIP_ARM]] ], [ [[V1_PRE]], %[[CALL_ARM]] ]
; CHECK-NEXT:    ret i64 [[V1]]
;
entry:
  %v0 = load i64, ptr %p, align 8
  %cmp = icmp slt i64 %v0, 0
  br i1 %cmp, label %call_arm, label %skip_arm

call_arm:
  call void @clobber(ptr %p)
  br label %merge

skip_arm:
  br label %merge

merge:
  %v1 = load i64, ptr %p, align 8
  ret i64 %v1
}

;--- Pattern 2: Single-predecessor PRE ---

; Load in a single-pred block; merge point is one hop back.
define i64 @single_pred_one_hop(ptr %p) {
; CHECK-LABEL: define i64 @single_pred_one_hop(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[V0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[V1_PRE:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V1:%.*]] = phi i64 [ [[V0]], %[[COND_FALSE]] ], [ [[V1_PRE]], %[[COND_TRUE]] ]
; CHECK-NEXT:    ret i64 [[V1]]
;
entry:
  %v0 = load i64, ptr %p, align 8
  %cmp = icmp slt i64 %v0, 0
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:
  call void @clobber(ptr %p)
  br label %merge

cond.false:
  br label %merge

merge:                                    ; 2 preds — effective merge point
  br label %use_block

use_block:                                ; 1 pred — load is here
  %v1 = load i64, ptr %p, align 8
  ret i64 %v1
}

; Load in a single-pred block; merge point is two hops back.
define i64 @single_pred_two_hops(ptr %p) {
; CHECK-LABEL: define i64 @single_pred_two_hops(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[V0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[V1_PRE:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V1:%.*]] = phi i64 [ [[V0]], %[[COND_FALSE]] ], [ [[V1_PRE]], %[[COND_TRUE]] ]
; CHECK-NEXT:    ret i64 [[V1]]
;
entry:
  %v0 = load i64, ptr %p, align 8
  %cmp = icmp slt i64 %v0, 0
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:
  call void @clobber(ptr %p)
  br label %merge

cond.false:
  br label %merge

merge:
  br label %middle

middle:                                   ; single pred
  br label %use_block

use_block:                                ; single pred — load is here
  %v1 = load i64, ptr %p, align 8
  ret i64 %v1
}

;--- Cascading PRE ---

; Repeated diamonds with calls. GVN PREs each load of %p at successive
; merge points, using the previous PRE's result on the clean path.
; %v1 is in a 2-pred block (Pattern 1), %v2 is behind a 1-pred block
; (Pattern 2). Both should be PRE'd.
define i64 @cascading_diamonds(ptr %p) {
; CHECK-LABEL: define i64 @cascading_diamonds(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i64 [[V0]], 0
; CHECK-NEXT:    br i1 [[CMP1]], label %[[CALL1:.*]], label %[[SKIP1:.*]]
; CHECK:       [[CALL1]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[V1_PRE:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    br label %[[MERGE1:.*]]
; CHECK:       [[SKIP1]]:
; CHECK-NEXT:    br label %[[MERGE1]]
; CHECK:       [[MERGE1]]:
; CHECK-NEXT:    [[V1:%.*]] = phi i64 [ [[V0]], %[[SKIP1]] ], [ [[V1_PRE]], %[[CALL1]] ]
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i64 [[V1]], 100
; CHECK-NEXT:    br i1 [[CMP2]], label %[[CALL2:.*]], label %[[SKIP2:.*]]
; CHECK:       [[CALL2]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    [[V2_PRE:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    br label %[[MERGE2:.*]]
; CHECK:       [[SKIP2]]:
; CHECK-NEXT:    br label %[[MERGE2]]
; CHECK:       [[MERGE2]]:
; CHECK-NEXT:    [[V2:%.*]] = phi i64 [ [[V1]], %[[SKIP2]] ], [ [[V2_PRE]], %[[CALL2]] ]
; CHECK-NEXT:    ret i64 [[V2]]
;
entry:
  %v0 = load i64, ptr %p, align 8
  %cmp1 = icmp slt i64 %v0, 0
  br i1 %cmp1, label %call1, label %skip1

call1:
  call void @clobber(ptr %p)
  br label %merge1

skip1:
  br label %merge1

merge1:
  %v1 = load i64, ptr %p, align 8
  %cmp2 = icmp sgt i64 %v1, 100
  br i1 %cmp2, label %call2, label %skip2

call2:
  call void @clobber(ptr %p)
  br label %merge2

skip2:
  br label %merge2

merge2:
  br label %use_block

use_block:
  %v2 = load i64, ptr %p, align 8
  ret i64 %v2
}

;--- Negative test ---

; Clobber between merge and load: the store to %p in the single-pred
; chain means the load depends on that store. PRE should NOT apply.
define i64 @single_pred_with_clobber(ptr %p) {
; CHECK-LABEL: define i64 @single_pred_with_clobber(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[V0:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i64 [[V0]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    store i64 42, ptr [[P]], align 8
; CHECK-NEXT:    ret i64 42
;
entry:
  %v0 = load i64, ptr %p, align 8
  %cmp = icmp slt i64 %v0, 0
  br i1 %cmp, label %cond.true, label %cond.false

cond.true:
  call void @clobber(ptr %p)
  br label %merge

cond.false:
  br label %merge

merge:
  br label %use_block

use_block:
  store i64 42, ptr %p, align 8
  %v1 = load i64, ptr %p, align 8        ; depends on the store, not merge
  ret i64 %v1
}

declare void @clobber(ptr)
