; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn -newgvn-enable-pre=true -newgvn-enable-load-pre=true < %s | FileCheck %s

; Transitive availability: the load in %merge is partially redundant.
; Both predecessors are unavailable directly, but the value is available
; transitively — through stores on each path.

; Diamond with stores on both sides → load fully eliminated (NumUnavail 2→0).
define i32 @diamond_stores(ptr %p, i1 %cond) {
; CHECK-LABEL: define i32 @diamond_stores(
; CHECK-SAME: ptr [[P:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[LEFT:.*]], label %[[RIGHT:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    store i32 42, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[RIGHT]]:
; CHECK-NEXT:    store i32 99, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 99, %[[RIGHT]] ], [ 42, %[[LEFT]] ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
entry:
  store i32 1, ptr %p
  br i1 %cond, label %left, label %right

left:
  store i32 42, ptr %p
  br label %merge

right:
  store i32 99, ptr %p
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Diamond where one arm is transparent (no clobber) and the other stores.
; PRE should insert a load on the transparent path.
define i32 @diamond_one_store(ptr %p, i1 %cond) {
; CHECK-LABEL: define i32 @diamond_one_store(
; CHECK-SAME: ptr [[P:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 1, ptr [[P]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[LEFT:.*]], label %[[RIGHT:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    store i32 42, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[RIGHT]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 1, %[[RIGHT]] ], [ 42, %[[LEFT]] ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
entry:
  store i32 1, ptr %p
  br i1 %cond, label %left, label %right

left:
  store i32 42, ptr %p
  br label %merge

right:
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Three-way merge: stores on two paths, transparent on one.
define i32 @three_way_merge(ptr %p, i32 %sel) {
; CHECK-LABEL: define i32 @three_way_merge(
; CHECK-SAME: ptr [[P:%.*]], i32 [[SEL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    switch i32 [[SEL]], label %[[PATH_C:.*]] [
; CHECK-NEXT:      i32 0, label %[[PATH_A:.*]]
; CHECK-NEXT:      i32 1, label %[[PATH_B:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[PATH_A]]:
; CHECK-NEXT:    store i32 10, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[PATH_B]]:
; CHECK-NEXT:    store i32 20, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[PATH_C]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 20, %[[PATH_B]] ], [ 10, %[[PATH_A]] ], [ 0, %[[PATH_C]] ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
entry:
  store i32 0, ptr %p
  switch i32 %sel, label %path_c [
  i32 0, label %path_a
  i32 1, label %path_b
  ]

path_a:
  store i32 10, ptr %p
  br label %merge

path_b:
  store i32 20, ptr %p
  br label %merge

path_c:
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

; Deep chain: store is 3 blocks before merge, all transparent in between.
; Transitive walk should reach the store through intermediate blocks.
define i32 @deep_chain(ptr %p, i1 %c1, i1 %c2) {
; CHECK-LABEL: define i32 @deep_chain(
; CHECK-SAME: ptr [[P:%.*]], i1 [[C1:%.*]], i1 [[C2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 55, ptr [[P]], align 4
; CHECK-NEXT:    br i1 [[C1]], label %[[BB2:.*]], label %[[SIDE:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    br i1 [[C2]], label %[[BB3:.*]], label %[[SIDE]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[SIDE]]:
; CHECK-NEXT:    call void @may_clobber(ptr [[P]])
; CHECK-NEXT:    [[V_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[V_PRE_PHI:%.*]] = phi i32 [ [[V_PRE]], %[[SIDE]] ], [ 55, %[[BB3]] ]
; CHECK-NEXT:    ret i32 [[V_PRE_PHI]]
;
entry:
  store i32 55, ptr %p
  br label %bb1

bb1:
  br i1 %c1, label %bb2, label %side

bb2:
  br i1 %c2, label %bb3, label %side

bb3:
  br label %merge

side:
  call void @may_clobber(ptr %p)
  br label %merge

merge:
  %v = load i32, ptr %p
  ret i32 %v
}

declare void @may_clobber(ptr)
