; XFAIL: *
; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

  %struct.s_segment_inf = type { float, i32, i16, i16, float, float, i32, float, float }

define void @print_arch(ptr %arch_file, i32 %route_type, i64 %det_routing_arch.0.0, i64 %det_routing_arch.0.1, i64 %det_routing_arch.0.2, i64 %det_routing_arch.0.3, i64 %det_routing_arch.0.4, ptr %segment_inf, i64 %timing_inf.0.0, i64 %timing_inf.0.1, i64 %timing_inf.0.2, i64 %timing_inf.0.3, i64 %timing_inf.0.4, i32 %timing_inf.1) {
; CHECK-LABEL: define void @print_arch(
; CHECK-SAME: ptr [[ARCH_FILE:%.*]], i32 [[ROUTE_TYPE:%.*]], i64 [[DET_ROUTING_ARCH_0_0:%.*]], i64 [[DET_ROUTING_ARCH_0_1:%.*]], i64 [[DET_ROUTING_ARCH_0_2:%.*]], i64 [[DET_ROUTING_ARCH_0_3:%.*]], i64 [[DET_ROUTING_ARCH_0_4:%.*]], ptr [[SEGMENT_INF:%.*]], i64 [[TIMING_INF_0_0:%.*]], i64 [[TIMING_INF_0_1:%.*]], i64 [[TIMING_INF_0_2:%.*]], i64 [[TIMING_INF_0_3:%.*]], i64 [[TIMING_INF_0_4:%.*]], i32 [[TIMING_INF_1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[ENTRY_BB278_CRIT_EDGE:.*]], label %[[BB344:.*]]
; CHECK:       [[ENTRY_BB278_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB278:.*]]
; CHECK:       [[BB278]]:
; CHECK-NEXT:    br i1 false, label %[[BB278]], label %[[BB278_BB344_CRIT_EDGE:.*]]
; CHECK:       [[BB278_BB344_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB344]]
; CHECK:       [[BB344]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 false, label %bb278, label %bb344

bb278:		; preds = %bb278, %entry
  br i1 false, label %bb278, label %bb344

bb344:		; preds = %bb278, %entry
  %tmp38758 = load i16, ptr null, align 2		; <i16> [#uses=0]
  ret void
}
