; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

  %struct.TypHeader = type { i32, ptr, [3 x i8], i8 }

define ptr @LtRec(ptr %hdL, ptr %hdR) {
; CHECK-LABEL: define ptr @LtRec(
; CHECK-SAME: ptr [[HDL:%.*]], ptr [[HDR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[BB556_PREHEADER:.*]], label %[[BB534_PREHEADER:.*]]
; CHECK:       [[BB534_PREHEADER]]:
; CHECK-NEXT:    ret ptr null
; CHECK:       [[BB556_PREHEADER]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB_NPH23:.*]], label %[[BB675_PREHEADER:.*]]
; CHECK:       [[BB_NPH23]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    ret ptr null
; CHECK:       [[BB656:.*]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB656_BB684_CRIT_EDGE:.*]], label %[[BB656_BB656_CRIT_EDGE:.*]]
; CHECK:       [[BB656_BB656_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB656]]
; CHECK:       [[BB656_BB684_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB684:.*]]
; CHECK:       [[BB684]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB924_PREHEADER:.*]], label %[[BB684_BB675_OUTER_CRIT_EDGE:.*]]
; CHECK:       [[BB684_BB675_OUTER_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB675_OUTER:.*]]
; CHECK:       [[BB675_OUTER]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB675_OUTER_BB684_CRIT_EDGE:.*]], label %[[BB675_OUTER_BB656_CRIT_EDGE:.*]]
; CHECK:       [[BB675_OUTER_BB656_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB656]]
; CHECK:       [[BB675_OUTER_BB684_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB684]]
; CHECK:       [[BB675_PREHEADER]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB675_OUTER]]
; CHECK:       [[BB924_PREHEADER]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    ret ptr null
;
entry:
  br i1 false, label %bb556.preheader, label %bb534.preheader

bb534.preheader:		; preds = %entry
  ret ptr null

bb556.preheader:		; preds = %entry
  %tmp56119 = getelementptr %struct.TypHeader, ptr %hdR, i32 0, i32 0		; <ptr> [#uses=1]
  %tmp56220 = load i32, ptr %tmp56119		; <i32> [#uses=0]
  br i1 false, label %bb.nph23, label %bb675.preheader

bb.nph23:		; preds = %bb556.preheader
  ret ptr null

bb656:		; preds = %bb675.outer, %bb656
  %tmp678 = load i32, ptr %tmp677		; <i32> [#uses=0]
  br i1 false, label %bb684, label %bb656

bb684:		; preds = %bb675.outer, %bb656
  br i1 false, label %bb924.preheader, label %bb675.outer

bb675.outer:		; preds = %bb675.preheader, %bb684
  %tmp67812 = load i32, ptr %tmp67711		; <i32> [#uses=0]
  br i1 false, label %bb684, label %bb656

bb675.preheader:		; preds = %bb556.preheader
  %tmp67711 = getelementptr %struct.TypHeader, ptr %hdR, i32 0, i32 0		; <ptr> [#uses=1]
  %tmp677 = getelementptr %struct.TypHeader, ptr %hdR, i32 0, i32 0		; <ptr> [#uses=1]
  br label %bb675.outer

bb924.preheader:		; preds = %bb684
  ret ptr null
}
