; XFAIL: *
; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

  %struct.PerlInterpreter = type { i8 }
@PL_sv_count = external global i32		; <ptr> [#uses=2]

define void @perl_destruct(ptr %sv_interp) {
; CHECK-LABEL: define void @perl_destruct(
; CHECK-SAME: ptr [[SV_INTERP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT25:.*]], label %[[COND_TRUE16:.*]]
; CHECK:       [[COND_TRUE16]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT25]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT33:.*]], label %[[COND_TRUE32:.*]]
; CHECK:       [[COND_TRUE32]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT33]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT61:.*]], label %[[COND_TRUE_I46:.*]]
; CHECK:       [[COND_TRUE_I46]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT61]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT69:.*]], label %[[COND_TRUE66:.*]]
; CHECK:       [[COND_TRUE66]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT69]]:
; CHECK-NEXT:    br i1 false, label %[[PERL_SAFEFREE_EXIT52:.*]], label %[[COND_TRUE_I50:.*]]
; CHECK:       [[COND_TRUE_I50]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PERL_SAFEFREE_EXIT52]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT80:.*]], label %[[COND_TRUE77:.*]]
; CHECK:       [[COND_TRUE77]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT80]]:
; CHECK-NEXT:    br i1 false, label %[[PERL_SAFEFREE_EXIT56:.*]], label %[[COND_TRUE_I54:.*]]
; CHECK:       [[COND_TRUE_I54]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PERL_SAFEFREE_EXIT56]]:
; CHECK-NEXT:    br i1 false, label %[[PERL_SAFEFREE_EXIT60:.*]], label %[[COND_TRUE_I58:.*]]
; CHECK:       [[COND_TRUE_I58]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PERL_SAFEFREE_EXIT60]]:
; CHECK-NEXT:    br i1 false, label %[[PERL_SAFEFREE_EXIT64:.*]], label %[[COND_TRUE_I62:.*]]
; CHECK:       [[COND_TRUE_I62]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PERL_SAFEFREE_EXIT64]]:
; CHECK-NEXT:    br i1 false, label %[[PERL_SAFEFREE_EXIT68:.*]], label %[[COND_TRUE_I66:.*]]
; CHECK:       [[COND_TRUE_I66]]:
; CHECK-NEXT:    ret void
; CHECK:       [[PERL_SAFEFREE_EXIT68]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT150:.*]], label %[[COND_TRUE23_I:.*]]
; CHECK:       [[COND_TRUE23_I]]:
; CHECK-NEXT:    ret void
; CHECK:       [[COND_NEXT150]]:
; CHECK-NEXT:    [[TMP16092:%.*]] = load i32, ptr @PL_sv_count, align 4
; CHECK-NEXT:    br label %[[COND_NEXT165:.*]]
; CHECK:       [[BB157:.*]]:
; CHECK-NEXT:    [[TMP158:%.*]] = load i32, ptr @PL_sv_count, align 4
; CHECK-NEXT:    br label %[[COND_NEXT165]]
; CHECK:       [[COND_NEXT165]]:
; CHECK-NEXT:    br i1 false, label %[[BB171:.*]], label %[[BB157]]
; CHECK:       [[BB171]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 false, label %cond_next25, label %cond_true16

cond_true16:		; preds = %entry
  ret void

cond_next25:		; preds = %entry
  br i1 false, label %cond_next33, label %cond_true32

cond_true32:		; preds = %cond_next25
  ret void

cond_next33:		; preds = %cond_next25
  br i1 false, label %cond_next61, label %cond_true.i46

cond_true.i46:		; preds = %cond_next33
  ret void

cond_next61:		; preds = %cond_next33
  br i1 false, label %cond_next69, label %cond_true66

cond_true66:		; preds = %cond_next61
  ret void

cond_next69:		; preds = %cond_next61
  br i1 false, label %Perl_safefree.exit52, label %cond_true.i50

cond_true.i50:		; preds = %cond_next69
  ret void

Perl_safefree.exit52:		; preds = %cond_next69
  br i1 false, label %cond_next80, label %cond_true77

cond_true77:		; preds = %Perl_safefree.exit52
  ret void

cond_next80:		; preds = %Perl_safefree.exit52
  br i1 false, label %Perl_safefree.exit56, label %cond_true.i54

cond_true.i54:		; preds = %cond_next80
  ret void

Perl_safefree.exit56:		; preds = %cond_next80
  br i1 false, label %Perl_safefree.exit60, label %cond_true.i58

cond_true.i58:		; preds = %Perl_safefree.exit56
  ret void

Perl_safefree.exit60:		; preds = %Perl_safefree.exit56
  br i1 false, label %Perl_safefree.exit64, label %cond_true.i62

cond_true.i62:		; preds = %Perl_safefree.exit60
  ret void

Perl_safefree.exit64:		; preds = %Perl_safefree.exit60
  br i1 false, label %Perl_safefree.exit68, label %cond_true.i66

cond_true.i66:		; preds = %Perl_safefree.exit64
  ret void

Perl_safefree.exit68:		; preds = %Perl_safefree.exit64
  br i1 false, label %cond_next150, label %cond_true23.i

cond_true23.i:		; preds = %Perl_safefree.exit68
  ret void

cond_next150:		; preds = %Perl_safefree.exit68
  %tmp16092 = load i32, ptr @PL_sv_count, align 4		; <i32> [#uses=0]
  br label %cond_next165

bb157:		; preds = %cond_next165
  %tmp158 = load i32, ptr @PL_sv_count, align 4		; <i32> [#uses=0]
  br label %cond_next165

cond_next165:		; preds = %bb157, %cond_next150
  br i1 false, label %bb171, label %bb157

bb171:		; preds = %cond_next165
  ret void
}
