; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

  %struct.ggBRDF = type { ptr }
  %struct.ggBox3 = type { %struct.ggPoint3, %struct.ggPoint3 }
  %struct.ggMaterialRecord = type { %struct.ggPoint2, %struct.ggBox3, %struct.ggBox3, %struct.ggSpectrum, %struct.ggSpectrum, %struct.ggSpectrum, ptr, i32, i32, i32, i32 }
  %struct.ggONB3 = type { %struct.ggPoint3, %struct.ggPoint3, %struct.ggPoint3 }
  %struct.ggPoint2 = type { [2 x double] }
  %struct.ggPoint3 = type { [3 x double] }
  %struct.ggSpectrum = type { [8 x float] }
  %struct.mrViewingHitRecord = type { double, %struct.ggPoint3, %struct.ggONB3, %struct.ggPoint2, double, %struct.ggSpectrum, %struct.ggSpectrum, i32, i32, i32, i32 }
  %struct.mrXEllipticalCylinder = type { %struct.ggBRDF, float, float, float, float, float, float }

define i32 @_ZNK21mrZEllipticalCylinder10viewingHitERK6ggRay3dddR18mrViewingHitRecordR16ggMaterialRecord(ptr %this, ptr %ray, double %unnamed_arg, double %tmin, double %tmax, ptr %VHR, ptr %unnamed_arg2) {
; CHECK-LABEL: define i32 @_ZNK21mrZEllipticalCylinder10viewingHitERK6ggRay3dddR18mrViewingHitRecordR16ggMaterialRecord(
; CHECK-SAME: ptr [[THIS:%.*]], ptr [[RAY:%.*]], double [[UNNAMED_ARG:%.*]], double [[TMIN:%.*]], double [[TMAX:%.*]], ptr [[VHR:%.*]], ptr [[UNNAMED_ARG2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP80_I:%.*]] = getelementptr [[STRUCT_MRVIEWINGHITRECORD:%.*]], ptr [[VHR]], i32 0, i32 1, i32 0, i32 0
; CHECK-NEXT:    store double 0.000000e+00, ptr [[TMP80_I]], align 8
; CHECK-NEXT:    br i1 false, label %[[ENTRY_RETURN_CRIT_EDGE:.*]], label %[[COND_NEXT_I:.*]]
; CHECK:       [[ENTRY_RETURN_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[COND_NEXT_I]]:
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT_I_RETURN_CRIT_EDGE:.*]], label %[[COND_TRUE:.*]]
; CHECK:       [[COND_NEXT_I_RETURN_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[COND_TRUE]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    ret i32 0
;
entry:
  %tmp80.i = getelementptr %struct.mrViewingHitRecord, ptr %VHR, i32 0, i32 1, i32 0, i32 0		; <ptr> [#uses=1]
  store double 0.000000e+00, ptr %tmp80.i
  br i1 false, label %return, label %cond_next.i

cond_next.i:		; preds = %entry
  br i1 false, label %return, label %cond_true

cond_true:		; preds = %cond_next.i
  %tmp3.i8 = getelementptr %struct.mrViewingHitRecord, ptr %VHR, i32 0, i32 1, i32 0, i32 0		; <ptr> [#uses=1]
  %tmp46 = load double, ptr %tmp3.i8		; <double> [#uses=0]
  ret i32 1

return:		; preds = %cond_next.i, %entry
  ret i32 0
}
