; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s

@bsLive = external global i32		; <ptr> [#uses=2]

define i32 @bsR(i32 %n) {
; CHECK-LABEL: define i32 @bsR(
; CHECK-SAME: i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[COND_NEXT:.*]], label %[[ENTRY_BB19_CRIT_EDGE:.*]]
; CHECK:       [[ENTRY_BB19_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB19:.*]]
; CHECK:       [[COND_NEXT]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB19]]
; CHECK:       [[BB19]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  br i1 false, label %cond_next, label %bb19

cond_next:		; preds = %entry
  store i32 0, ptr @bsLive, align 4
  br label %bb19

bb19:		; preds = %cond_next, %entry
  %tmp29 = load i32, ptr @bsLive, align 4		; <i32> [#uses=0]
  ret i32 0
}
