; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; Cached results must be added to and verified against the visited sets.
; PR3217

define fastcc void @gen_field_die(ptr %decl) nounwind {
; CHECK-LABEL: define fastcc void @gen_field_die(
; CHECK-SAME: ptr [[DECL:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 false, label %[[BB203:.*]], label %[[BB202:.*]]
; CHECK:       [[BB202]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB203]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB207:.*]], label %[[BB204:.*]]
; CHECK:       [[BB204]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB208:.*]]
; CHECK:       [[BB207]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB208]]
; CHECK:       [[BB208]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    unreachable
;
entry:
  br i1 false, label %bb203, label %bb202

bb202:		; preds = %entry
  unreachable

bb203:		; preds = %entry
  %tmp = getelementptr i32, ptr %decl, i32 1		; <ptr> [#uses=1]
  %tmp1 = load i32, ptr %tmp, align 4		; <i32> [#uses=0]
  br i1 false, label %bb207, label %bb204

bb204:		; preds = %bb203
  %tmp2 = getelementptr i32, ptr %decl, i32 1		; <ptr> [#uses=1]
  br label %bb208

bb207:		; preds = %bb203
  br label %bb208

bb208:		; preds = %bb207, %bb204
  %iftmp.1374.0.in = phi ptr [ null, %bb207 ], [ %tmp2, %bb204 ]		; <ptr> [#uses=1]
  %iftmp.1374.0 = load i32, ptr %iftmp.1374.0.in		; <i32> [#uses=0]
  unreachable
}
