; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; PR2032
; XFAIL: *

define i32 @sscal(i32 %n, double %sa1, ptr %sx, i32 %incx) {
; CHECK-LABEL: define i32 @sscal(
; CHECK-SAME: i32 [[N:%.*]], double [[SA1:%.*]], ptr [[SX:%.*]], i32 [[INCX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SX_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[SX]], ptr [[SX_ADDR]], align 4
; CHECK-NEXT:    br label %[[BB33:.*]]
; CHECK:       [[BB:.*]]:
; CHECK-NEXT:    [[TMP27:%.*]] = load ptr, ptr [[SX_ADDR]], align 4
; CHECK-NEXT:    store float 0.000000e+00, ptr [[TMP27]], align 4
; CHECK-NEXT:    store ptr null, ptr [[SX_ADDR]], align 4
; CHECK-NEXT:    br label %[[BB33]]
; CHECK:       [[BB33]]:
; CHECK-NEXT:    br i1 false, label %[[BB]], label %[[RETURN:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL59:%.*]] = load i32, ptr null, align 4
; CHECK-NEXT:    ret i32 [[RETVAL59]]
;
entry:
  %sx_addr = alloca ptr		; <ptr> [#uses=3]
  store ptr %sx, ptr %sx_addr, align 4
  br label %bb33

bb:		; preds = %bb33
  %tmp27 = load ptr, ptr %sx_addr, align 4		; <ptr> [#uses=1]
  store float 0.000000e+00, ptr %tmp27, align 4
  store ptr null, ptr %sx_addr, align 4
  br label %bb33

bb33:		; preds = %bb, %entry
  br i1 false, label %bb, label %return

return:		; preds = %bb33
  %retval59 = load i32, ptr null, align 4		; <i32> [#uses=1]
  ret i32 %retval59
}
