; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i386-apple-darwin7"
@sort_value = external global [256 x i32], align 32		; <ptr> [#uses=2]

define i32 @Quiesce(i32 %alpha, i32 %beta, i32 %wtm, i32 %ply) nounwind {
; CHECK-LABEL: define i32 @Quiesce(
; CHECK-SAME: i32 [[ALPHA:%.*]], i32 [[BETA:%.*]], i32 [[WTM:%.*]], i32 [[PLY:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[BB22:.*]]
; CHECK:       [[BB22]]:
; CHECK-NEXT:    br i1 false, label %[[BB22_BB23_CRIT_EDGE:.*]], label %[[BB22_BB22_CRIT_EDGE:.*]]
; CHECK:       [[BB22_BB22_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB22]]
; CHECK:       [[BB22_BB23_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB23:.*]]
; CHECK:       [[BB23]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[BB23_BB23_CRIT_EDGE:.*]], label %[[BB23_BB22_CRIT_EDGE:.*]]
; CHECK:       [[BB23_BB22_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB22]]
; CHECK:       [[BB23_BB23_CRIT_EDGE]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB23]]
;
entry:
  br label %bb22

bb22:		; preds = %bb23, %bb22, %entry
  br i1 false, label %bb23, label %bb22

bb23:		; preds = %bb23, %bb22
  %sortv.233 = phi ptr [ @sort_value, %bb22 ], [ %sortv.2, %bb23 ]		; <ptr> [#uses=1]
  %0 = load i32, ptr %sortv.233, align 4		; <i32> [#uses=0]
  %sortv.2 = getelementptr [256 x i32], ptr @sort_value, i32 0, i32 0		; <ptr> [#uses=1]
  br i1 false, label %bb23, label %bb22
}
