; XFAIL: *
; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i386-apple-darwin7"

define i32 @main(i32 %argc, ptr %argv) nounwind {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: i32 [[ARGC:%.*]], ptr [[ARGV:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[BB84:.*]]
; CHECK:       [[BB41:.*]]:
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[OPT_0:%.*]], i32 1
; CHECK-NEXT:    switch i32 0, label %[[BB81:.*]] [
; CHECK-NEXT:      i32 102, label %[[BB82:.*]]
; CHECK-NEXT:      i32 110, label %[[BB79:.*]]
; CHECK-NEXT:      i32 118, label %[[BB80:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[BB79]]:
; CHECK-NEXT:    br label %[[BB82]]
; CHECK:       [[BB80]]:
; CHECK-NEXT:    ret i32 0
; CHECK:       [[BB81]]:
; CHECK-NEXT:    ret i32 1
; CHECK:       [[BB82]]:
; CHECK-NEXT:    [[OPT_0]] = phi ptr [ inttoptr (i32 1 to ptr), %[[BB84]] ], [ [[TMP1]], %[[BB79]] ], [ [[TMP1]], %[[BB41]] ]
; CHECK-NEXT:    br i1 false, label %[[BB82_BB84_CRIT_EDGE:.*]], label %[[BB41]]
; CHECK:       [[BB82_BB84_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB84]]
; CHECK:       [[BB84]]:
; CHECK-NEXT:    br label %[[BB82]]
;
entry:
  br label %bb84

bb41:		; preds = %bb82
  %tmp = load i8, ptr %opt.0, align 1		; <i8> [#uses=0]
  %tmp1 = getelementptr i8, ptr %opt.0, i32 1		; <ptr> [#uses=2]
  switch i32 0, label %bb81 [
  i32 102, label %bb82
  i32 110, label %bb79
  i32 118, label %bb80
  ]

bb79:		; preds = %bb41
  br label %bb82

bb80:		; preds = %bb41
  ret i32 0

bb81:		; preds = %bb41
  ret i32 1

bb82:		; preds = %bb84, %bb79, %bb41
  %opt.0 = phi ptr [ %tmp3, %bb84 ], [ %tmp1, %bb79 ], [ %tmp1, %bb41 ]		; <ptr> [#uses=3]
  %tmp2 = load i8, ptr %opt.0, align 1		; <i8> [#uses=0]
  br i1 false, label %bb84, label %bb41

bb84:		; preds = %bb82, %entry
  %tmp3 = getelementptr i8, ptr null, i32 1		; <ptr> [#uses=1]
  br label %bb82
}
