; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=newgvn -S < %s | FileCheck %s
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-f128:128:128-n8:16:32:64"

@nuls = external global [10 x i8]

define fastcc void @p_ere(i1 %arg) nounwind {
; CHECK-LABEL: define fastcc void @p_ere(
; CHECK-SAME: i1 [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<L18>.i":
; CHECK-NEXT:    br i1 [[ARG]], label %"<bb 3>.i30.i", label %[[DOEMIT_EXIT51_I:.*]]
; CHECK:       "<bb 3>.i30.i":
; CHECK-NEXT:    unreachable
; CHECK:       [[DOEMIT_EXIT51_I]]:
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L19>.i":
; CHECK-NEXT:    br i1 [[ARG]], label %"<bb 3>.i55.i", label %[[DOEMIT_EXIT76_I:.*]]
; CHECK:       "<bb 3>.i55.i":
; CHECK-NEXT:    unreachable
; CHECK:       [[DOEMIT_EXIT76_I]]:
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L98>.i":
; CHECK-NEXT:    store ptr @nuls, ptr undef, align 8
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L99>.i":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L24>.i":
; CHECK-NEXT:    br i1 [[ARG]], label %"<L24>.i.<bb 53>.i_crit_edge", label %"<bb 35>.i"
; CHECK:       "<L24>.i.<bb 53>.i_crit_edge":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<bb 35>.i":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L28>.i":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L29>.i":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<L39>.i":
; CHECK-NEXT:    br label %"<bb 53>.i"
; CHECK:       "<bb 53>.i":
; CHECK-NEXT:    br i1 [[ARG]], label %"<bb 54>.i", label %"<bb 53>.i.<bb 5>_crit_edge"
; CHECK:       "<bb 53>.i.<bb 5>_crit_edge":
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<bb 54>.i":
; CHECK-NEXT:    br i1 true, label %"<bb 54>.i.<bb 5>_crit_edge", label %"<bb 58>.i"
; CHECK:       "<bb 54>.i.<bb 5>_crit_edge":
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<bb 58>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 true, label %"<bb 58>.i.<bb 64>.i_crit_edge", label %"<bb 59>.i"
; CHECK:       "<bb 58>.i.<bb 64>.i_crit_edge":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %"<bb 64>.i"
; CHECK:       "<bb 59>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %"<bb 64>.i"
; CHECK:       "<bb 64>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    switch i32 undef, label %"<bb 64>.i.<bb 5>_crit_edge" [
; CHECK-NEXT:      i32 42, label %"<L54>.i"
; CHECK-NEXT:      i32 43, label %"<L55>.i"
; CHECK-NEXT:      i32 63, label %"<L56>.i"
; CHECK-NEXT:      i32 123, label %"<bb 5>.i258.i"
; CHECK-NEXT:    ]
; CHECK:       "<bb 64>.i.<bb 5>_crit_edge":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<L54>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 true, label %"<bb 3>.i105.i", label %[[DOEMIT_EXIT127_I:.*]]
; CHECK:       "<bb 3>.i105.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    unreachable
; CHECK:       [[DOEMIT_EXIT127_I]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    unreachable
; CHECK:       "<L55>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 true, label %"<bb 3>.i157.i", label %"<L55>.i.<bb 5>_crit_edge"
; CHECK:       "<L55>.i.<bb 5>_crit_edge":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<bb 3>.i157.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    unreachable
; CHECK:       "<L56>.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %"<bb 5>"
; CHECK:       "<bb 5>.i258.i":
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    unreachable
; CHECK:       "<bb 5>":
; CHECK-NEXT:    switch i32 undef, label %"<L39>.i" [
; CHECK-NEXT:      i32 36, label %"<L19>.i"
; CHECK-NEXT:      i32 94, label %"<L18>.i"
; CHECK-NEXT:      i32 124, label %"<L98>.i"
; CHECK-NEXT:      i32 42, label %"<bb 5>.<L99>.i_crit_edge"
; CHECK-NEXT:      i32 43, label %"<bb 5>.<L99>.i_crit_edge1"
; CHECK-NEXT:      i32 46, label %"<L24>.i"
; CHECK-NEXT:      i32 63, label %"<bb 5>.<L99>.i_crit_edge2"
; CHECK-NEXT:      i32 91, label %"<L28>.i"
; CHECK-NEXT:      i32 92, label %"<L29>.i"
; CHECK-NEXT:    ]
; CHECK:       "<bb 5>.<L99>.i_crit_edge2":
; CHECK-NEXT:    br label %"<L99>.i"
; CHECK:       "<bb 5>.<L99>.i_crit_edge1":
; CHECK-NEXT:    br label %"<L99>.i"
; CHECK:       "<bb 5>.<L99>.i_crit_edge":
; CHECK-NEXT:    br label %"<L99>.i"
;
entry:
  br label %"<bb 5>"

"<L18>.i":
  br i1 %arg, label %"<bb 3>.i30.i", label %doemit.exit51.i

"<bb 3>.i30.i":
  unreachable

doemit.exit51.i:
  br label %"<bb 53>.i"

"<L19>.i":
  br i1 %arg, label %"<bb 3>.i55.i", label %doemit.exit76.i

"<bb 3>.i55.i":
  unreachable

doemit.exit76.i:
  br label %"<bb 53>.i"

"<L98>.i":
  store ptr @nuls, ptr undef, align 8
  br label %"<bb 53>.i"

"<L99>.i":
  br label %"<bb 53>.i"

"<L24>.i":
  br i1 %arg, label %"<bb 53>.i", label %"<bb 35>.i"

"<bb 35>.i":
  br label %"<bb 53>.i"

"<L28>.i":
  br label %"<bb 53>.i"

"<L29>.i":
  br label %"<bb 53>.i"

"<L39>.i":
  br label %"<bb 53>.i"

"<bb 53>.i":
  %wascaret_2.i = phi i32 [ 0, %"<L39>.i" ], [ 0, %"<L29>.i" ], [ 0, %"<L28>.i" ], [ 0, %"<bb 35>.i" ], [ 0, %"<L99>.i" ], [ 0, %"<L98>.i" ], [ 0, %doemit.exit76.i ], [ 1, %doemit.exit51.i ], [ 0, %"<L24>.i" ]
  %D.5496_84.i = load ptr, ptr undef, align 8
  br i1 %arg, label %"<bb 54>.i", label %"<bb 5>"

"<bb 54>.i":
  br i1 %arg, label %"<bb 5>", label %"<bb 58>.i"

"<bb 58>.i":
  br i1 %arg, label %"<bb 64>.i", label %"<bb 59>.i"

"<bb 59>.i":
  br label %"<bb 64>.i"

"<bb 64>.i":
  switch i32 undef, label %"<bb 5>" [
  i32 42, label %"<L54>.i"
  i32 43, label %"<L55>.i"
  i32 63, label %"<L56>.i"
  i32 123, label %"<bb 5>.i258.i"
  ]

"<L54>.i":
  br i1 %arg, label %"<bb 3>.i105.i", label %doemit.exit127.i

"<bb 3>.i105.i":
  unreachable

doemit.exit127.i:
  unreachable

"<L55>.i":
  br i1 %arg, label %"<bb 3>.i157.i", label %"<bb 5>"

"<bb 3>.i157.i":
  unreachable

"<L56>.i":
  br label %"<bb 5>"

"<bb 5>.i258.i":
  unreachable

"<bb 5>":
  switch i32 undef, label %"<L39>.i" [
  i32 36, label %"<L19>.i"
  i32 94, label %"<L18>.i"
  i32 124, label %"<L98>.i"
  i32 42, label %"<L99>.i"
  i32 43, label %"<L99>.i"
  i32 46, label %"<L24>.i"
  i32 63, label %"<L99>.i"
  i32 91, label %"<L28>.i"
  i32 92, label %"<L29>.i"
  ]
}
