; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; NewGVN eliminates the redundant bitcast but does not merge blocks
; (unlike GVN which merges block1 and block2).

define i32 @main() {
; CHECK-LABEL: define i32 @main() {
; CHECK-NEXT:  block1:
; CHECK-NEXT:    br label %block2
; CHECK:       block2:
; CHECK-NEXT:    ret i32 0
;
block1:
  %z1 = bitcast i32 0 to i32
  br label %block2
block2:
  %z2 = bitcast i32 0 to i32
  ret i32 %z2
}
