; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=newgvn < %s | FileCheck %s
; Check that loads from calloc are recognized as being zero.

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"

; Function Attrs: nounwind uwtable
define i32 @test1() {
; CHECK-LABEL: define i32 @test1() {
; CHECK-NEXT:    [[TMP1:%.*]] = tail call noalias ptr @calloc(i64 1, i64 4)
; CHECK-NEXT:    ret i32 0
;
  %1 = tail call noalias ptr @calloc(i64 1, i64 4)
  ; This load is trivially constant zero
  %2 = load i32, ptr %1, align 4
  ret i32 %2


; CHECK_NO_LIBCALLS-LABEL: @test1(
; CHECK_NO_LIBCALLS: load
; CHECK_NO_LIBCALLS: ret i32 %

}

define i32 @as_invoke(i1 %c) personality ptr undef {
; CHECK-LABEL: define i32 @as_invoke(
; CHECK-SAME: i1 [[C:%.*]]) personality ptr undef {
; CHECK-NEXT:  [[BB3:.*:]]
; CHECK-NEXT:    [[MEM:%.*]] = invoke noalias ptr @calloc(i64 1, i64 4)
; CHECK-NEXT:            to label %[[BB4:.*]] unwind label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[LP:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    ret i32 0
; CHECK:       [[BB4]]:
; CHECK-NEXT:    ret i32 0
;
bb3:
  %mem = invoke noalias ptr @calloc(i64 1, i64 4)
  to label %bb4 unwind label %bb1

bb1:
  %lp = landingpad { ptr, i32 } cleanup
  ret i32 0

bb4:
  ; This load is trivially constant zero
  %res = load i32, ptr %mem, align 4
  ret i32 %res


; CHECK_NO_LIBCALLS-LABEL: @as_invoke(
; CHECK_NO_LIBCALLS: load
; CHECK_NO_LIBCALLS: ret i32 %
}

declare noalias ptr @calloc(i64, i64) allockind("alloc,zeroed") allocsize(0,1)
