; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; XFAIL: *
; RUN: opt -S -passes=newgvn < %s | FileCheck %s

define i64 @test(ptr noalias %p, ptr noalias %q) {
; CHECK-LABEL: define i64 @test(
; CHECK-SAME: ptr noalias [[P:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr [[Q]], ptr [[P]], align 8
; CHECK-NEXT:    br i1 false, label %[[IF:.*]], label %[[MERGE:.*]]
; CHECK:       [[IF]]:
; CHECK-NEXT:    call void @clobber(ptr [[P]])
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    store i64 1, ptr [[Q]], align 4
; CHECK-NEXT:    [[Q3:%.*]] = getelementptr i64, ptr [[Q]], i64 1
; CHECK-NEXT:    store i64 2, ptr [[Q3]], align 4
; CHECK-NEXT:    ret i64 1
;
entry:
  store ptr %q, ptr %p
  br i1 false, label %if, label %merge

if:
  call void @clobber(ptr %p)
  br label %merge

merge:
  %q2 = load ptr, ptr %p
  store i64 1, ptr %q2
  %v = load i64, ptr %q
  %q3 = getelementptr i64, ptr %q, i64 %v
  store i64 2, ptr %q3
  %v2 = load i64, ptr %q
  ret i64 %v2
}

declare void @clobber(ptr %p)
