; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -disable-basic-aa -passes=newgvn -S < %s | FileCheck %s
; NewGVN now forwards the load through the inttoptr/store via cross-type
; forwarding (matching GVN MemDep behavior).

target datalayout = "e-p:32:32:32"
define <2 x i32> @test1() {
; CHECK-LABEL: define <2 x i32> @test1() {
; CHECK-NEXT:    [[V1:%.*]] = alloca <2 x i32>, align 8
; CHECK-NEXT:    call void @anything(ptr [[V1]])
; CHECK-NEXT:    [[V2:%.*]] = load <2 x i32>, ptr [[V1]], align 8
; CHECK-NEXT:    [[V3:%.*]] = inttoptr <2 x i32> [[V2]] to <2 x ptr>
; CHECK-NEXT:    store <2 x ptr> [[V3]], ptr [[V1]], align 8
; CHECK-NEXT:    ret <2 x i32> [[V2]]
;
  %v1 = alloca <2 x i32>
  call void @anything(ptr %v1)
  %v2 = load <2 x i32>, ptr %v1
  %v3 = inttoptr <2 x i32> %v2 to <2 x ptr>
  store <2 x ptr> %v3, ptr %v1
  %v5 = load <2 x i32>, ptr %v1
  ret <2 x i32> %v5
}

declare void @anything(ptr)
