; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=newgvn -S -o - < %s | FileCheck %s
; NewGVN now forwards loads across different types (ptr -> i64 via ptrtoint)
; and handles unreachable blocks by inserting poison stores.

target triple = "x86_64-unknown-linux-gnu"

define i64 @foo(ptr %arrayidx) {
; CHECK-LABEL: define i64 @foo(
; CHECK-SAME: ptr [[ARRAYIDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = load ptr, ptr [[ARRAYIDX]], align 8
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[ENTRY2:.*:]]
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[LOAD:%.*]] = ptrtoint ptr [[P]] to i64
; CHECK-NEXT:    ret i64 [[LOAD]]
;
entry:
  %p = load ptr, ptr %arrayidx, align 8
  %cmpnull = icmp eq ptr %p, null
  br label %BB2

entry2:                                           ; No predecessors!
  br label %BB2

BB2:                                              ; preds = %entry2, %entry
  %load = load i64, ptr %arrayidx, align 8
  ret i64 %load
}
