; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=newgvn < %s | FileCheck %s

define i32 @main(i64 %x, ptr %d, ptr noalias %p) {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: i64 [[X:%.*]], ptr [[D:%.*]], ptr noalias [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[T1_PRE_PRE_PRE:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[T2_PRE_PRE_PRE1:%.*]] = load ptr, ptr [[T1_PRE_PRE_PRE]], align 8, !tbaa [[ANYPTR_TBAA0:![0-9]+]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[T2_PRE_PRE_PRE_PHI:%.*]] = phi ptr [ [[T2_PRE_PRE_PHI:%.*]], %[[LOOP_LATCH:.*]] ], [ [[T2_PRE_PRE_PRE1]], %[[ENTRY]] ]
; CHECK-NEXT:    [[T1_PRE_PRE_PRE_PHI:%.*]] = phi ptr [ [[T1_PRE_PRE_PHI:%.*]], %[[LOOP_LATCH]] ], [ [[T1_PRE_PRE_PRE]], %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    [[T2_PRE_PRE_PHI]] = phi ptr [ [[T2_PRE_PRE_PRE:%.*]], %[[LOOP2_LATCH:.*]] ], [ [[T2_PRE_PRE_PRE_PHI]], %[[LOOP]] ]
; CHECK-NEXT:    [[T1_PRE_PRE_PHI]] = phi ptr [ [[T5_PRE_PHI:%.*]], %[[LOOP2_LATCH]] ], [ [[T1_PRE_PRE_PRE_PHI]], %[[LOOP]] ]
; CHECK-NEXT:    br label %[[LOOP3:.*]]
; CHECK:       [[LOOP3]]:
; CHECK-NEXT:    [[T2_PRE_PRE_PRE]] = phi ptr [ [[T6_PRE_PHI:%.*]], %[[LOOP3_LATCH:.*]] ], [ [[T2_PRE_PRE_PHI]], %[[LOOP2]] ]
; CHECK-NEXT:    [[T1_PRE_PHI:%.*]] = phi ptr [ [[T5_PRE_PHI]], %[[LOOP3_LATCH]] ], [ [[T1_PRE_PRE_PHI]], %[[LOOP2]] ]
; CHECK-NEXT:    [[T3_PRE_PRE_PRE:%.*]] = load ptr, ptr [[T2_PRE_PRE_PRE]], align 8
; CHECK-NEXT:    br i1 false, label %[[LOOP3_LATCH]], label %[[FOR_BODY_LR_PH_I:.*]]
; CHECK:       [[FOR_BODY_LR_PH_I]]:
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    [[T5_PRE:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[T6_PRE:%.*]] = load ptr, ptr [[T5_PRE]], align 8, !tbaa [[ANYPTR_TBAA0]]
; CHECK-NEXT:    br label %[[LOOP3_LATCH]]
; CHECK:       [[LOOP3_LATCH]]:
; CHECK-NEXT:    [[T6_PRE_PHI]] = phi ptr [ [[T6_PRE]], %[[FOR_BODY_LR_PH_I]] ], [ [[T2_PRE_PRE_PRE]], %[[LOOP3]] ]
; CHECK-NEXT:    [[T5_PRE_PHI]] = phi ptr [ [[T5_PRE]], %[[FOR_BODY_LR_PH_I]] ], [ [[T1_PRE_PRE_PHI]], %[[LOOP3]] ]
; CHECK-NEXT:    br i1 false, label %[[LOOP2_LATCH]], label %[[LOOP3]]
; CHECK:       [[LOOP2_LATCH]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br i1 false, label %[[LOOP2]], label %[[LOOP_LATCH]]
; CHECK:       [[LOOP_LATCH]]:
; CHECK-NEXT:    store i8 poison, ptr null, align 1
; CHECK-NEXT:    br label %[[LOOP]]
;
entry:
  br label %loop

loop:
  br label %loop2

loop2:
  br label %loop3

loop3:
  %t1 = load ptr, ptr %p, align 8
  %t2 = load ptr, ptr %t1, align 8, !tbaa !0
  %t3 = load ptr, ptr %t2, align 8
  %t4 = load i8, ptr %t3, align 1
  %tobool.not2.i = icmp eq i64 %x, 0
  br i1 false, label %loop3.latch, label %for.body.lr.ph.i

for.body.lr.ph.i:
  store i32 0, ptr %p, align 4
  br label %w.exit.loopexit

w.exit.loopexit:
  br label %loop3.latch

loop3.latch:
  %t5 = load ptr, ptr %p, align 8
  %t6 = load ptr, ptr %t5, align 8, !tbaa !0
  %t7 = load ptr, ptr %t6, align 8
  br i1 false, label %loop2.latch, label %loop3

loop2.latch:
  br i1 false, label %loop2, label %loop.latch

loop.latch:
  store i32 0, ptr %d, align 4, !tbaa !4
  br label %loop
}

!0 = !{!1, !1, i64 0}
!1 = !{!"any pointer", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
!4 = !{!5, !5, i64 0}
!5 = !{!"int", !2, i64 0}
;.
; CHECK: [[ANYPTR_TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"any pointer", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C/C++ TBAA"}
;.
