; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; Test PHI translation for load elimination.
;
; @g: may-alias pointers through PHI — load is kept (same as GVN XFAIL).
; @phi_trans_alloca: noalias allocas through PHI — load is eliminated via
;   PHI translation (-newgvn-enable-phi-translation).

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i386-apple-darwin7"

; May-alias case: %b and %c could alias, so the load cannot be eliminated.
define i32 @g(ptr %b, ptr %c) nounwind {
; CHECK-LABEL: define i32 @g(
; CHECK-SAME: ptr [[B:%.*]], ptr [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 1, ptr [[B]], align 4
; CHECK-NEXT:    store i32 2, ptr [[C]], align 4
; CHECK-NEXT:    [[T1:%.*]] = icmp eq ptr [[B]], null
; CHECK-NEXT:    br i1 [[T1]], label %[[BB:.*]], label %[[ENTRY_BB2_CRIT_EDGE:.*]]
; CHECK:       [[ENTRY_BB2_CRIT_EDGE]]:
; CHECK-NEXT:    [[CV_PRE:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    br label %[[BB2:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[CV:%.*]] = phi i32 [ 2, %[[BB]] ], [ [[CV_PRE]], %[[ENTRY_BB2_CRIT_EDGE]] ]
; CHECK-NEXT:    [[C_ADDR_0:%.*]] = phi ptr [ [[B]], %[[ENTRY_BB2_CRIT_EDGE]] ], [ [[C]], %[[BB]] ]
; CHECK-NEXT:    ret i32 [[CV]]
;
; NOPHITRANS-LABEL: define i32 @g(
; NOPHITRANS-SAME: ptr [[B:%.*]], ptr [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; NOPHITRANS-NEXT:  [[ENTRY:.*:]]
; NOPHITRANS-NEXT:    store i32 1, ptr [[B]], align 4
; NOPHITRANS-NEXT:    store i32 2, ptr [[C]], align 4
; NOPHITRANS-NEXT:    [[T1:%.*]] = icmp eq ptr [[B]], null
; NOPHITRANS-NEXT:    br i1 [[T1]], label %[[BB:.*]], label %[[ENTRY_BB2_CRIT_EDGE:.*]]
; NOPHITRANS:       [[ENTRY_BB2_CRIT_EDGE]]:
; NOPHITRANS-NEXT:    [[CV_PRE:%.*]] = load i32, ptr [[B]], align 4
; NOPHITRANS-NEXT:    br label %[[BB2:.*]]
; NOPHITRANS:       [[BB]]:
; NOPHITRANS-NEXT:    br label %[[BB2]]
; NOPHITRANS:       [[BB2]]:
; NOPHITRANS-NEXT:    [[CV_PRE_PHI:%.*]] = phi i32 [ 2, %[[BB]] ], [ [[CV_PRE]], %[[ENTRY_BB2_CRIT_EDGE]] ]
; NOPHITRANS-NEXT:    [[C_ADDR_0:%.*]] = phi ptr [ [[B]], %[[ENTRY_BB2_CRIT_EDGE]] ], [ [[C]], %[[BB]] ]
; NOPHITRANS-NEXT:    ret i32 [[CV_PRE_PHI]]
;
entry:
  store i32 1, ptr %b
  store i32 2, ptr %c

  %t1 = icmp eq ptr %b, null		; <i1> [#uses=1]
  br i1 %t1, label %bb, label %bb2

bb:		; preds = %entry
  br label %bb2

bb2:		; preds = %bb1, %bb
  %c_addr.0 = phi ptr [ %b, %entry ], [ %c, %bb ]		; <ptr> [#uses=1]
  %cv = load i32, ptr %c_addr.0, align 4		; <i32> [#uses=1]
  ret i32 %cv
}

; No-alias case: allocas cannot alias, so PHI translation can eliminate the load.
define i32 @phi_trans_alloca(i1 %cond) {
; CHECK-LABEL: define i32 @phi_trans_alloca(
; CHECK-SAME: i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 42, ptr [[A]], align 4
; CHECK-NEXT:    store i32 97, ptr [[B]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 97, %[[ELSE]] ], [ 42, %[[THEN]] ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %[[THEN]] ], [ [[B]], %[[ELSE]] ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
; NOPHITRANS-LABEL: define i32 @phi_trans_alloca(
; NOPHITRANS-SAME: i1 [[COND:%.*]]) {
; NOPHITRANS-NEXT:  [[ENTRY:.*:]]
; NOPHITRANS-NEXT:    [[A:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    [[B:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    store i32 42, ptr [[A]], align 4
; NOPHITRANS-NEXT:    store i32 97, ptr [[B]], align 4
; NOPHITRANS-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; NOPHITRANS:       [[THEN]]:
; NOPHITRANS-NEXT:    br label %[[MERGE:.*]]
; NOPHITRANS:       [[ELSE]]:
; NOPHITRANS-NEXT:    br label %[[MERGE]]
; NOPHITRANS:       [[MERGE]]:
; NOPHITRANS-NEXT:    [[VAL:%.*]] = phi i32 [ 97, %[[ELSE]] ], [ 42, %[[THEN]] ]
; NOPHITRANS-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %[[THEN]] ], [ [[B]], %[[ELSE]] ]
; NOPHITRANS-NEXT:    ret i32 [[VAL]]
;
entry:
  %a = alloca i32
  %b = alloca i32
  store i32 42, ptr %a
  store i32 97, ptr %b
  br i1 %cond, label %then, label %else

then:
  br label %merge

else:
  br label %merge

merge:
  %ptr = phi ptr [%a, %then], [%b, %else]
  %val = load i32, ptr %ptr
  ret i32 %val
}

; Verify the flag disables PHI translation.
; RUN: opt < %s -passes=newgvn -newgvn-enable-phi-translation=false -S | FileCheck %s --check-prefix=NOPHITRANS

define i32 @phi_trans_disabled(i1 %cond) {
; CHECK-LABEL: define i32 @phi_trans_disabled(
; CHECK-SAME: i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 42, ptr [[A]], align 4
; CHECK-NEXT:    store i32 97, ptr [[B]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; CHECK:       [[THEN]]:
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[ELSE]]:
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 97, %[[ELSE]] ], [ 42, %[[THEN]] ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %[[THEN]] ], [ [[B]], %[[ELSE]] ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
; NOPHITRANS-LABEL: define i32 @phi_trans_disabled(
; NOPHITRANS-SAME: i1 [[COND:%.*]]) {
; NOPHITRANS-NEXT:  [[ENTRY:.*:]]
; NOPHITRANS-NEXT:    [[A:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    [[B:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    store i32 42, ptr [[A]], align 4
; NOPHITRANS-NEXT:    store i32 97, ptr [[B]], align 4
; NOPHITRANS-NEXT:    br i1 [[COND]], label %[[THEN:.*]], label %[[ELSE:.*]]
; NOPHITRANS:       [[THEN]]:
; NOPHITRANS-NEXT:    br label %[[MERGE:.*]]
; NOPHITRANS:       [[ELSE]]:
; NOPHITRANS-NEXT:    br label %[[MERGE]]
; NOPHITRANS:       [[MERGE]]:
; NOPHITRANS-NEXT:    [[VAL:%.*]] = phi i32 [ 97, %[[ELSE]] ], [ 42, %[[THEN]] ]
; NOPHITRANS-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %[[THEN]] ], [ [[B]], %[[ELSE]] ]
; NOPHITRANS-NEXT:    ret i32 [[VAL]]
;
entry:
  %a = alloca i32
  %b = alloca i32
  store i32 42, ptr %a
  store i32 97, ptr %b
  br i1 %cond, label %then, label %else

then:
  br label %merge

else:
  br label %merge

merge:
  %ptr = phi ptr [%a, %then], [%b, %else]
  %val = load i32, ptr %ptr
  ret i32 %val
}
