; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=newgvn -S | FileCheck %s
; Test PHI translation for load elimination.
;
; @g: may-alias pointers through PHI — load is kept (same as GVN XFAIL).
; @phi_trans_alloca: noalias allocas through PHI — load is eliminated via
;   PHI translation (-newgvn-enable-phi-translation).

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"
target triple = "i386-apple-darwin7"

; May-alias case: %b and %c could alias, so the load cannot be eliminated.
define i32 @g(ptr %b, ptr %c) nounwind {
; CHECK-LABEL: define i32 @g(
; CHECK-SAME: ptr [[B:%.*]], ptr [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store i32 1, ptr [[B]], align 4
; CHECK-NEXT:    store i32 2, ptr [[C]], align 4
; CHECK-NEXT:    [[T1:%.*]] = icmp eq ptr [[B]], null
; CHECK-NEXT:    br i1 [[T1]], label %bb, label %bb2
; CHECK:       bb:
; CHECK-NEXT:    br label %bb2
; CHECK:       bb2:
; CHECK-NEXT:    [[C_ADDR_0:%.*]] = phi ptr [ [[B]], %entry ], [ [[C]], %bb ]
; CHECK-NEXT:    [[CV:%.*]] = load i32, ptr [[C_ADDR_0]], align 4
; CHECK-NEXT:    ret i32 [[CV]]
;
entry:
  store i32 1, ptr %b
  store i32 2, ptr %c

  %t1 = icmp eq ptr %b, null		; <i1> [#uses=1]
  br i1 %t1, label %bb, label %bb2

bb:		; preds = %entry
  br label %bb2

bb2:		; preds = %bb1, %bb
  %c_addr.0 = phi ptr [ %b, %entry ], [ %c, %bb ]		; <ptr> [#uses=1]
  %cv = load i32, ptr %c_addr.0, align 4		; <i32> [#uses=1]
  ret i32 %cv
}

; No-alias case: allocas cannot alias, so PHI translation can eliminate the load.
define i32 @phi_trans_alloca(i1 %cond) {
; CHECK-LABEL: define i32 @phi_trans_alloca(
; CHECK-SAME: i1 [[COND:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 42, ptr [[A]], align 4
; CHECK-NEXT:    store i32 97, ptr [[B]], align 4
; CHECK-NEXT:    br i1 [[COND]], label %then, label %else
; CHECK:       then:
; CHECK-NEXT:    br label %merge
; CHECK:       else:
; CHECK-NEXT:    br label %merge
; CHECK:       merge:
; CHECK-NEXT:    [[PHIOFOPS:%.*]] = phi i32 [ 97, %else ], [ 42, %then ]
; CHECK-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %then ], [ [[B]], %else ]
; CHECK-NEXT:    ret i32 [[PHIOFOPS]]
;
entry:
  %a = alloca i32
  %b = alloca i32
  store i32 42, ptr %a
  store i32 97, ptr %b
  br i1 %cond, label %then, label %else

then:
  br label %merge

else:
  br label %merge

merge:
  %ptr = phi ptr [%a, %then], [%b, %else]
  %val = load i32, ptr %ptr
  ret i32 %val
}

; Verify the flag disables PHI translation.
; RUN: opt < %s -passes=newgvn -newgvn-enable-phi-translation=false -S | FileCheck %s --check-prefix=NOPHITRANS

define i32 @phi_trans_disabled(i1 %cond) {
; NOPHITRANS-LABEL: define i32 @phi_trans_disabled(
; NOPHITRANS-SAME: i1 [[COND:%.*]]) {
; NOPHITRANS-NEXT:  entry:
; NOPHITRANS-NEXT:    [[A:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    [[B:%.*]] = alloca i32, align 4
; NOPHITRANS-NEXT:    store i32 42, ptr [[A]], align 4
; NOPHITRANS-NEXT:    store i32 97, ptr [[B]], align 4
; NOPHITRANS-NEXT:    br i1 [[COND]], label %then, label %else
; NOPHITRANS:       then:
; NOPHITRANS-NEXT:    br label %merge
; NOPHITRANS:       else:
; NOPHITRANS-NEXT:    br label %merge
; NOPHITRANS:       merge:
; NOPHITRANS-NEXT:    [[PTR:%.*]] = phi ptr [ [[A]], %then ], [ [[B]], %else ]
; NOPHITRANS-NEXT:    [[VAL:%.*]] = load i32, ptr [[PTR]], align 4
; NOPHITRANS-NEXT:    ret i32 [[VAL]]
;
entry:
  %a = alloca i32
  %b = alloca i32
  store i32 42, ptr %a
  store i32 97, ptr %b
  br i1 %cond, label %then, label %else

then:
  br label %merge

else:
  br label %merge

merge:
  %ptr = phi ptr [%a, %then], [%b, %else]
  %val = load i32, ptr %ptr
  ret i32 %val
}
