; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S < %s -passes=newgvn | FileCheck %s

define void @test(i1 %cmp19, ptr %p) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i1 [[CMP19:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[CMP19]], label %[[WHILE_BODY_LR_PH:.*]], label %[[FOR_COND_PREHEADER:.*]]
; CHECK:       [[WHILE_BODY_LR_PH]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND_PREHEADER]]:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %cmp19, label %while.body.lr.ph, label %for.cond.preheader

while.body.lr.ph:                                 ; preds = %entry
  %.pre1 = load <vscale x 2 x double>, ptr %p, align 16
  %0 = extractelement <vscale x 2 x double> %.pre1, i64 0
  ret void

for.cond.preheader:                               ; preds = %entry
  %.pre = load double, ptr %p, align 8
  %add = fadd double %.pre, 0.000000e+00
  ret void
}
