; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=newgvn -S < %s | FileCheck %s
; NewGVN propagates equalities from trunc nuw (matching GVN behavior
; via -newgvn-enable-trunc-equality): replaces %v with 0 in the false
; branch and 1 in the true branch.

define void @test(ptr %p, i64 %v) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[P:%.*]], i64 [[V:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TR:%.*]] = trunc nuw i64 [[V]] to i1
; CHECK-NEXT:    br i1 [[TR]], label %ret, label %store
; CHECK:       store:
; CHECK-NEXT:    store i64 0, ptr [[P]], align 4
; CHECK-NEXT:    ret void
; CHECK:       ret:
; CHECK-NEXT:    store i64 1, ptr [[P]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %tr = trunc nuw i64 %v to i1
  br i1 %tr, label %ret, label %store

store:
  store i64 %v, ptr %p
  ret void

ret:
  store i64 %v, ptr %p
  ret void
}
