; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -enable-load-pre -S | FileCheck %s
; XFAIL: *
  %struct.VEC_rtx_base = type { i32, i32, [1 x ptr] }
  %struct.VEC_rtx_gc = type { %struct.VEC_rtx_base }
  %struct.block_symbol = type { [3 x %struct.cgraph_rtl_info], ptr, i64 }
  %struct.cgraph_rtl_info = type { i32 }
  %struct.object_block = type { ptr, i32, i64, ptr, ptr }
  %struct.rtvec_def = type { i32, [1 x ptr] }
  %struct.rtx_def = type { i16, i8, i8, %struct.u }
  %struct.section = type { %struct.unnamed_section }
  %struct.u = type { %struct.block_symbol }
  %struct.unnamed_section = type { %struct.cgraph_rtl_info, ptr, ptr, ptr }

declare ptr @gen_rtvec(i32, ...)

declare ptr @plus_constant(ptr, i64)

declare ptr @gen_rtx_fmt_Ei(i32, i32, ptr, i32)

declare i32 @local_symbolic_operand(ptr, i32)

define ptr @legitimize_pic_address(ptr %orig, ptr %reg) nounwind {
; CHECK-LABEL: define ptr @legitimize_pic_address(
; CHECK-SAME: ptr [[ORIG:%.*]], ptr [[REG:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[IFTMP_1532:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[ORIG]], ptr null, align 8
; CHECK-NEXT:    br i1 false, label %[[ENTRY_BB96_CRIT_EDGE:.*]], label %[[BB59:.*]]
; CHECK:       [[ENTRY_BB96_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB96:.*]]
; CHECK:       [[BB59]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @local_symbolic_operand(ptr undef, i32 0) #[[ATTR0]]
; CHECK-NEXT:    br i1 false, label %[[BB59_BB96_CRIT_EDGE:.*]], label %[[BB63:.*]]
; CHECK:       [[BB59_BB96_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[BB96]]
; CHECK:       [[BB63]]:
; CHECK-NEXT:    br i1 false, label %[[BB64:.*]], label %[[BB74:.*]]
; CHECK:       [[BB64]]:
; CHECK-NEXT:    br i1 false, label %[[BB72:.*]], label %[[BB65:.*]]
; CHECK:       [[BB65]]:
; CHECK-NEXT:    br label %[[BB72]]
; CHECK:       [[BB72]]:
; CHECK-NEXT:    br label %[[BB74]]
; CHECK:       [[BB74]]:
; CHECK-NEXT:    br i1 false, label %[[BB75:.*]], label %[[BB76:.*]]
; CHECK:       [[BB75]]:
; CHECK-NEXT:    br label %[[BB76]]
; CHECK:       [[BB76]]:
; CHECK-NEXT:    br i1 false, label %[[BB77:.*]], label %[[BB84:.*]]
; CHECK:       [[BB77]]:
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 0
; CHECK-NEXT:    unreachable
; CHECK:       [[BB84]]:
; CHECK-NEXT:    br i1 false, label %[[BB85:.*]], label %[[BB86:.*]]
; CHECK:       [[BB85]]:
; CHECK-NEXT:    br label %[[BB87:.*]]
; CHECK:       [[BB86]]:
; CHECK-NEXT:    br label %[[BB87]]
; CHECK:       [[BB87]]:
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @gen_rtx_fmt_Ei(i32 16, i32 0, ptr null, i32 1) #[[ATTR0]]
; CHECK-NEXT:    br i1 false, label %[[BB89:.*]], label %[[BB90:.*]]
; CHECK:       [[BB89]]:
; CHECK-NEXT:    br label %[[BB91:.*]]
; CHECK:       [[BB90]]:
; CHECK-NEXT:    br label %[[BB91]]
; CHECK:       [[BB91]]:
; CHECK-NEXT:    br i1 false, label %[[BB92:.*]], label %[[BB93:.*]]
; CHECK:       [[BB92]]:
; CHECK-NEXT:    br label %[[BB94:.*]]
; CHECK:       [[BB93]]:
; CHECK-NEXT:    br label %[[BB94]]
; CHECK:       [[BB94]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB96]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ADDR]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [[STRUCT_RTX_DEF:%.*]], ptr [[TMP3]], i32 0, i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    br i1 false, label %[[BB147:.*]], label %[[BB97:.*]]
; CHECK:       [[BB97]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[ADDR]], align 4
; CHECK-NEXT:    br i1 false, label %[[BB147]], label %[[BB99:.*]]
; CHECK:       [[BB99]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB147]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[ADDR]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr [[STRUCT_RTX_DEF]], ptr [[TMP7]], i32 0, i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    br i1 false, label %[[BB164:.*]], label %[[BB148:.*]]
; CHECK:       [[BB148]]:
; CHECK-NEXT:    br i1 false, label %[[BB164]], label %[[BB149:.*]]
; CHECK:       [[BB149]]:
; CHECK-NEXT:    br i1 false, label %[[BB150:.*]], label %[[BB152:.*]]
; CHECK:       [[BB150]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB152]]:
; CHECK-NEXT:    br label %[[BB164]]
; CHECK:       [[BB164]]:
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 1
; CHECK-NEXT:    br i1 false, label %[[BB165:.*]], label %[[BB166:.*]]
; CHECK:       [[BB165]]:
; CHECK-NEXT:    br label %[[BB167:.*]]
; CHECK:       [[BB166]]:
; CHECK-NEXT:    br label %[[BB167]]
; CHECK:       [[BB167]]:
; CHECK-NEXT:    br i1 false, label %[[BB211:.*]], label %[[BB168:.*]]
; CHECK:       [[BB168]]:
; CHECK-NEXT:    br i1 false, label %[[BB211]], label %[[BB170:.*]]
; CHECK:       [[BB170]]:
; CHECK-NEXT:    br i1 false, label %[[BB172:.*]], label %[[BB181:.*]]
; CHECK:       [[BB172]]:
; CHECK-NEXT:    br i1 false, label %[[BB179:.*]], label %[[BB174:.*]]
; CHECK:       [[BB174]]:
; CHECK-NEXT:    br i1 false, label %[[BB177:.*]], label %[[BB175:.*]]
; CHECK:       [[BB175]]:
; CHECK-NEXT:    br i1 false, label %[[BB177]], label %[[BB176:.*]]
; CHECK:       [[BB176]]:
; CHECK-NEXT:    br label %[[BB178:.*]]
; CHECK:       [[BB177]]:
; CHECK-NEXT:    br label %[[BB178]]
; CHECK:       [[BB178]]:
; CHECK-NEXT:    br label %[[BB180:.*]]
; CHECK:       [[BB179]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB180]]:
; CHECK-NEXT:    br label %[[BB181]]
; CHECK:       [[BB181]]:
; CHECK-NEXT:    [[TMP11:%.*]] = call ptr (i32, ...) @gen_rtvec(i32 1, ptr null) #[[ATTR0]]
; CHECK-NEXT:    unreachable
; CHECK:       [[BB211]]:
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[ADDR]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 0
; CHECK-NEXT:    store ptr null, ptr null, align 4
; CHECK-NEXT:    br i1 false, label %[[BB212:.*]], label %[[BB213:.*]]
; CHECK:       [[BB212]]:
; CHECK-NEXT:    store ptr null, ptr [[IFTMP_1532]], align 4
; CHECK-NEXT:    br label %[[BB214:.*]]
; CHECK:       [[BB213]]:
; CHECK-NEXT:    store ptr null, ptr [[IFTMP_1532]], align 4
; CHECK-NEXT:    br label %[[BB214]]
; CHECK:       [[BB214]]:
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 1
; CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[IFTMP_1532]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr [[STRUCT_RTX_DEF]], ptr null, i32 0, i32 3
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr [[STRUCT_U:%.*]], ptr [[TMP16]], i32 0, i32 0
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr [1 x i64], ptr [[TMP17]], i32 0, i32 0
; CHECK-NEXT:    [[TMP19:%.*]] = call ptr @plus_constant(ptr null, i64 0) #[[ATTR0]]
; CHECK-NEXT:    unreachable
;
entry:
  %addr = alloca ptr		; <ptr> [#uses=5]
  %iftmp.1532 = alloca ptr		; <ptr> [#uses=3]
  store ptr %orig, ptr null
  %0 = load ptr, ptr null, align 4		; <ptr> [#uses=0]
  br i1 false, label %bb96, label %bb59

bb59:		; preds = %entry
  %1 = load ptr, ptr %addr, align 4		; <ptr> [#uses=1]
  %2 = call i32 @local_symbolic_operand(ptr %1, i32 0) nounwind		; <i32> [#uses=0]
  br i1 false, label %bb96, label %bb63

bb63:		; preds = %bb59
  br i1 false, label %bb64, label %bb74

bb64:		; preds = %bb63
  br i1 false, label %bb72, label %bb65

bb65:		; preds = %bb64
  br label %bb72

bb72:		; preds = %bb65, %bb64
  br label %bb74

bb74:		; preds = %bb72, %bb63
  br i1 false, label %bb75, label %bb76

bb75:		; preds = %bb74
  br label %bb76

bb76:		; preds = %bb75, %bb74
  br i1 false, label %bb77, label %bb84

bb77:		; preds = %bb76
  %3 = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 0		; <ptr> [#uses=0]
  unreachable

bb84:		; preds = %bb76
  br i1 false, label %bb85, label %bb86

bb85:		; preds = %bb84
  br label %bb87

bb86:		; preds = %bb84
  br label %bb87

bb87:		; preds = %bb86, %bb85
  %4 = call ptr @gen_rtx_fmt_Ei(i32 16, i32 0, ptr null, i32 1) nounwind		; <ptr> [#uses=0]
  br i1 false, label %bb89, label %bb90

bb89:		; preds = %bb87
  br label %bb91

bb90:		; preds = %bb87
  br label %bb91

bb91:		; preds = %bb90, %bb89
  br i1 false, label %bb92, label %bb93

bb92:		; preds = %bb91
  br label %bb94

bb93:		; preds = %bb91
  br label %bb94

bb94:		; preds = %bb93, %bb92
  unreachable

bb96:		; preds = %bb59, %entry
  %5 = load ptr, ptr %addr, align 4		; <ptr> [#uses=1]
  %6 = getelementptr %struct.rtx_def, ptr %5, i32 0, i32 0		; <ptr> [#uses=1]
  %7 = load i16, ptr %6, align 2		; <i16> [#uses=0]
  br i1 false, label %bb147, label %bb97

bb97:		; preds = %bb96
  %8 = load ptr, ptr %addr, align 4		; <ptr> [#uses=0]
  br i1 false, label %bb147, label %bb99

bb99:		; preds = %bb97
  unreachable

bb147:		; preds = %bb97, %bb96
  %9 = load ptr, ptr %addr, align 4		; <ptr> [#uses=1]
  %10 = getelementptr %struct.rtx_def, ptr %9, i32 0, i32 0		; <ptr> [#uses=1]
  %11 = load i16, ptr %10, align 2		; <i16> [#uses=0]
  br i1 false, label %bb164, label %bb148

bb148:		; preds = %bb147
  br i1 false, label %bb164, label %bb149

bb149:		; preds = %bb148
  br i1 false, label %bb150, label %bb152

bb150:		; preds = %bb149
  unreachable

bb152:		; preds = %bb149
  br label %bb164

bb164:		; preds = %bb152, %bb148, %bb147
  %12 = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 1		; <ptr> [#uses=0]
  br i1 false, label %bb165, label %bb166

bb165:		; preds = %bb164
  br label %bb167

bb166:		; preds = %bb164
  br label %bb167

bb167:		; preds = %bb166, %bb165
  br i1 false, label %bb211, label %bb168

bb168:		; preds = %bb167
  br i1 false, label %bb211, label %bb170

bb170:		; preds = %bb168
  br i1 false, label %bb172, label %bb181

bb172:		; preds = %bb170
  br i1 false, label %bb179, label %bb174

bb174:		; preds = %bb172
  br i1 false, label %bb177, label %bb175

bb175:		; preds = %bb174
  br i1 false, label %bb177, label %bb176

bb176:		; preds = %bb175
  br label %bb178

bb177:		; preds = %bb175, %bb174
  br label %bb178

bb178:		; preds = %bb177, %bb176
  br label %bb180

bb179:		; preds = %bb172
  br label %bb180

bb180:		; preds = %bb179, %bb178
  br label %bb181

bb181:		; preds = %bb180, %bb170
  %13 = call ptr (i32, ...) @gen_rtvec(i32 1, ptr null) nounwind		; <ptr> [#uses=0]
  unreachable

bb211:		; preds = %bb168, %bb167
  %14 = load ptr, ptr %addr, align 4		; <ptr> [#uses=0]
  %15 = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 0		; <ptr> [#uses=0]
  store ptr null, ptr null, align 4
  br i1 false, label %bb212, label %bb213

bb212:		; preds = %bb211
  store ptr null, ptr %iftmp.1532, align 4
  br label %bb214

bb213:		; preds = %bb211
  store ptr null, ptr %iftmp.1532, align 4
  br label %bb214

bb214:		; preds = %bb213, %bb212
  %16 = getelementptr [1 x %struct.cgraph_rtl_info], ptr null, i32 0, i32 1		; <ptr> [#uses=0]
  %17 = load ptr, ptr %iftmp.1532, align 4		; <ptr> [#uses=0]
  %18 = getelementptr %struct.rtx_def, ptr null, i32 0, i32 3		; <ptr> [#uses=1]
  %19 = getelementptr %struct.u, ptr %18, i32 0, i32 0		; <ptr> [#uses=1]
  %20 = getelementptr [1 x i64], ptr %19, i32 0, i32 0		; <ptr> [#uses=0]
  %21 = call ptr @plus_constant(ptr null, i64 0) nounwind		; <ptr> [#uses=0]
  unreachable
}
