; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=newgvn -S < %s | FileCheck %s
; This test checks if debug loc is propagated to load/store created by GVN/Instcombine.

; struct node {
;  int  *v;
; struct desc *descs;
; };

; struct desc {
;  struct node *node;
; };

; extern int bar(void *v, void* n);

; int test(struct desc *desc)
; {
;  void *v, *n;
;  v = !desc ? ((void *)0) : desc->node->v;  // Line 15
;  n = &desc->node->descs[0];                // Line 16
;  return bar(v, n);
; }

; Line 16, Column 13:
;   n = &desc->node->descs[0];
;              ^

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

%struct.desc = type { ptr }
%struct.node = type { ptr, ptr }

define i32 @test_no_null_opt(ptr readonly %desc) local_unnamed_addr #0 !dbg !4 {
; CHECK-LABEL: define i32 @test_no_null_opt(
; CHECK-SAME: ptr readonly [[DESC:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] !dbg [[DBG4:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp eq ptr [[DESC]], null
; CHECK-NEXT:    br i1 [[TOBOOL]], label %[[ENTRY_COND_END_CRIT_EDGE:.*]], label %[[COND_FALSE:.*]], !dbg [[DBG9:![0-9]+]]
; CHECK:       [[ENTRY_COND_END_CRIT_EDGE]]:
; CHECK-NEXT:    [[DOTPRE:%.*]] = load ptr, ptr [[DESC]], align 8, !dbg [[DBG10:![0-9]+]]
; CHECK-NEXT:    br label %[[COND_END:.*]], !dbg [[DBG9]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DESC]], align 8, !dbg [[DBG11:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    br label %[[COND_END]], !dbg [[DBG9]]
; CHECK:       [[COND_END]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi ptr [ [[TMP0]], %[[COND_FALSE]] ], [ [[DOTPRE]], %[[ENTRY_COND_END_CRIT_EDGE]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[TMP1]], %[[COND_FALSE]] ], [ null, %[[ENTRY_COND_END_CRIT_EDGE]] ], !dbg [[DBG9]]
; CHECK-NEXT:    [[DESCS:%.*]] = getelementptr inbounds [[STRUCT_NODE:%.*]], ptr [[TMP3]], i64 0, i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DESCS]], align 8
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @bar(ptr [[TMP2]], ptr [[TMP4]])
; CHECK-NEXT:    ret i32 [[CALL]]
;
entry:
  %tobool = icmp eq ptr %desc, null
  br i1 %tobool, label %cond.end, label %cond.false, !dbg !9
; ALL: %.pre = load ptr, ptr %desc, align 8, !dbg [[LOC_16_13:![0-9]+]]
; ALL: br i1 %tobool, label %cond.end, label %cond.false, !dbg [[LOC_15_6:![0-9]+]]
; ALL: cond.false:

cond.false:
  %0 = load ptr, ptr %desc, align 8, !dbg !11
  %1 = load ptr, ptr %0, align 8
  br label %cond.end, !dbg !9

cond.end:
; ALL: phi ptr [ %0, %cond.false ], [ null, %entry ]

  %2 = phi ptr [ %1, %cond.false ], [ null, %entry ], !dbg !9
  %3 = load ptr, ptr %desc, align 8, !dbg !10
  %descs = getelementptr inbounds %struct.node, ptr %3, i64 0, i32 1
  %4 = load ptr, ptr %descs, align 8
  %call = tail call i32 @bar(ptr %2, ptr %4)
  ret i32 %call
}
attributes #0 = { null_pointer_is_valid }

declare i32 @bar(ptr, ptr) local_unnamed_addr #1
!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, emissionKind: FullDebug)
!1 = !DIFile(filename: "test.c", directory: ".")
!2 = !{i32 2, !"Dwarf Version", i32 4}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "test_no_null_opt", scope: !1, file: !1, line: 12, type: !5, isLocal: false, isDefinition: true, scopeLine: 13, flags: DIFlagPrototyped, isOptimized: true, unit: !0, retainedNodes: !8)
!5 = !DISubroutineType(types: !6)
!6 = !{!7}
!7 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!8 = !{}
!9 = !DILocation(line: 15, column: 6, scope: !4)
!10 = !DILocation(line: 16, column: 13, scope: !4)
!11 = !DILocation(line: 15, column: 34, scope: !4)

;ALL: [[SCOPE:![0-9]+]] = distinct  !DISubprogram(name: "test_no_null_opt",{{.*}}
;ALL: [[LOC_16_13]] = !DILocation(line: 16, column: 13, scope: [[SCOPE]])
;ALL: [[LOC_15_6]] = !DILocation(line: 15, column: 6, scope: [[SCOPE]])
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C99, file: [[META1:![0-9]+]], isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}test.c", directory: {{.*}})
; CHECK: [[DBG4]] = distinct !DISubprogram(name: "test_no_null_opt", scope: [[META1]], file: [[META1]], line: 12, type: [[META5:![0-9]+]], scopeLine: 13, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META8:![0-9]+]])
; CHECK: [[META5]] = !DISubroutineType(types: [[META6:![0-9]+]])
; CHECK: [[META6]] = !{[[META7:![0-9]+]]}
; CHECK: [[META7]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META8]] = !{}
; CHECK: [[DBG9]] = !DILocation(line: 15, column: 6, scope: [[DBG4]])
; CHECK: [[DBG10]] = !DILocation(line: 16, column: 13, scope: [[DBG4]])
; CHECK: [[DBG11]] = !DILocation(line: 15, column: 34, scope: [[DBG4]])
;.
