; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=newgvn < %s | FileCheck %s --check-prefixes=CHECK,MDEP
; RUN: opt -S -passes=newgvn < %s | FileCheck %s --check-prefixes=CHECK,MSSA

define i32 @test1(ptr %p, i1 %C) {
; CHECK-LABEL: define i32 @test1(
; CHECK-SAME: ptr [[P:%.*]], i1 [[C:%.*]]) {
; CHECK-NEXT:  [[BLOCK1:.*:]]
; CHECK-NEXT:    br i1 [[C]], label %[[BLOCK2:.*]], label %[[BLOCK3:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    [[PRE_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[BLOCK4:.*]]
; CHECK:       [[BLOCK3]]:
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[BLOCK4]]
; CHECK:       [[BLOCK4]]:
; CHECK-NEXT:    [[PRE_PRE_PHI:%.*]] = phi i32 [ 0, %[[BLOCK3]] ], [ [[PRE_PRE]], %[[BLOCK2]] ]
; CHECK-NEXT:    ret i32 [[PRE_PRE_PHI]]
;
block1:
  br i1 %C, label %block2, label %block3

block2:
  br label %block4

block3:
  store i32 0, ptr %p
  br label %block4

block4:
  %PRE = load i32, ptr %p, !range !0, !invariant.group !1
  ret i32 %PRE
}


!0 = !{i32 40, i32 100}
!1 = !{!"magic ptr"}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; MDEP: {{.*}}
; MSSA: {{.*}}
