; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=newgvn -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128-ni:4"

define void @nipre(ptr noalias %p, ptr noalias %p2, i8 %jmp) {
; CHECK-LABEL: @nipre(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i8 [[JMP:%.*]], label [[C:%.*]] [
; CHECK-NEXT:      i8 0, label [[A:%.*]]
; CHECK-NEXT:      i8 1, label [[B:%.*]]
; CHECK-NEXT:    ]
; CHECK:       a:
; CHECK-NEXT:    [[L1:%.*]] = load ptr addrspace(4), ptr [[P:%.*]], align 8
; CHECK-NEXT:    store ptr addrspace(4) [[L1]], ptr [[P2:%.*]], align 8
; CHECK-NEXT:    br label [[TAIL:%.*]]
; CHECK:       b:
; CHECK-NEXT:    [[L2:%.*]] = load ptr addrspace(4), ptr [[P]], align 8
; CHECK-NEXT:    store ptr addrspace(4) [[L2]], ptr [[P2]], align 8
; CHECK-NEXT:    br label [[TAIL]]
; CHECK:       c:
; CHECK-NEXT:    [[L3_PRE:%.*]] = load ptr addrspace(4), ptr [[P]], align 8
; CHECK-NEXT:    br label [[TAIL]]
; CHECK:       tail:
; CHECK-NEXT:    [[L3:%.*]] = phi ptr addrspace(4) [ [[L3_PRE]], [[C]] ], [ [[L2]], [[B]] ], [ [[L1]], [[A]] ]
; CHECK-NEXT:    store ptr addrspace(4) [[L3]], ptr [[P2]], align 8
; CHECK-NEXT:    ret void
;

entry:
  switch i8 %jmp, label %c [ i8 0, label %a
  i8 1, label %b]
a:
  %l1 = load ptr addrspace(4), ptr %p
  store ptr addrspace(4) %l1, ptr %p2
  br label %tail
b:
  %l2 = load ptr addrspace(4), ptr %p
  store ptr addrspace(4) %l2, ptr %p2
  br label %tail
c:
  br label %tail
tail:
  %l3 = load ptr addrspace(4), ptr %p
  store ptr addrspace(4) %l3, ptr %p2
  ret void
}
