; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=newgvn -S < %s | FileCheck %s

@H = common global i32 0
@G = common global i32 0

define i32 @test(i1 %cond, i32 %v) nounwind {
;
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: i1 [[COND:%.*]], i32 [[V:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br i1 [[COND]], label %[[BB:.*]], label %[[BB1:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[ADD_1:%.*]] = add nuw nsw i32 [[V]], -1
; CHECK-NEXT:    store i32 [[ADD_1]], ptr @G, align 4
; CHECK-NEXT:    br label %[[MERGE:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    [[ADD_2_PRE:%.*]] = add i32 [[V]], -1
; CHECK-NEXT:    br label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[PRE_PHI:%.*]] = phi i32 [ [[ADD_2_PRE]], %[[BB1]] ], [ [[ADD_1]], %[[BB]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[PRE_PHI]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[ACTION:.*]], label %[[RETURN:.*]]
; CHECK:       [[ACTION]]:
; CHECK-NEXT:    store i32 [[PRE_PHI]], ptr @H, align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[P:%.*]] = phi i32 [ 0, %[[MERGE]] ], [ 1, %[[ACTION]] ]
; CHECK-NEXT:    ret i32 [[P]]
;
entry:
  br i1 %cond, label %bb, label %bb1

bb:
  %add.1 = add nuw nsw i32 %v, -1
  store i32 %add.1, ptr @G, align 4
  br label %merge

bb1:
  br label %merge

merge:
  %add.2 = add i32 %v, -1
  %cmp = icmp sgt i32 %add.2, 0
  br i1 %cmp, label %action, label %return

action:
  store i32 %add.2, ptr @H, align 4
  br label %return

return:
  %p = phi i32 [0, %merge], [1, %action]
  ret i32 %p
}

