; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=newgvn -S | FileCheck %s --check-prefixes=CHECK,MDEP
; RUN: opt < %s -passes=newgvn -S | FileCheck %s --check-prefixes=CHECK,MSSA

define i32 @main(ptr %p, i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: ptr [[P:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[BLOCK1:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], [[Y]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[BLOCK2:.*]], label %[[BLOCK3:.*]]
; CHECK:       [[BLOCK2]]:
; CHECK-NEXT:    [[DEAD_PRE:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[BLOCK4:.*]]
; CHECK:       [[BLOCK3]]:
; CHECK-NEXT:    store i32 0, ptr [[P]], align 4
; CHECK-NEXT:    br label %[[BLOCK4]]
; CHECK:       [[BLOCK4]]:
; CHECK-NEXT:    [[DEAD_PRE_PHI:%.*]] = phi i32 [ 0, %[[BLOCK3]] ], [ [[DEAD_PRE]], %[[BLOCK2]] ]
; CHECK-NEXT:    ret i32 [[DEAD_PRE_PHI]]
;
block1:
  %z = load i32, ptr %p
  %cmp = icmp eq i32 %x, %y
  br i1 %cmp, label %block2, label %block3

block2:
  br label %block4

block3:
  %b = bitcast i32 0 to i32
  store i32 %b, ptr %p
  br label %block4

block4:
  %DEAD = load i32, ptr %p
  ret i32 %DEAD
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; MDEP: {{.*}}
; MSSA: {{.*}}
