; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=newgvn -S < %s | FileCheck %s

define i8 @coerce_offset0_addrspacecast(i32 %V, ptr %P) {
; MDEP-LABEL: define i8 @coerce_offset0_addrspacecast(
; MDEP-SAME: i32 [[V:%.*]], ptr [[P:%.*]]) {
; MDEP-NEXT:    store i32 [[V]], ptr [[P]], align 4
; MDEP-NEXT:    [[TMP1:%.*]] = lshr i32 [[V]], 16
; MDEP-NEXT:    [[TMP2:%.*]] = trunc i32 [[TMP1]] to i8
; MDEP-NEXT:    ret i8 [[TMP2]]
;
;
; CHECK-LABEL: define i8 @coerce_offset0_addrspacecast(
; CHECK-SAME: i32 [[V:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    store i32 [[V]], ptr [[P]], align 4
; CHECK-NEXT:    [[P2:%.*]] = addrspacecast ptr [[P]] to ptr addrspace(1)
; CHECK-NEXT:    [[P3:%.*]] = getelementptr i8, ptr addrspace(1) [[P2]], i32 2
; CHECK-NEXT:    [[A:%.*]] = load i8, ptr addrspace(1) [[P3]], align 1
; CHECK-NEXT:    ret i8 [[A]]
;
  store i32 %V, ptr %P

  %P2 = addrspacecast ptr %P to ptr addrspace(1)
  %P3 = getelementptr i8, ptr addrspace(1) %P2, i32 2

  %A = load i8, ptr addrspace(1) %P3
  ret i8 %A
}
